### ISSUE TITLE
Tripal3: Search by feature IDs in URL

### ISSUE THREAD

**Issue by songtaogui** [tripal/tripal#1027]
Hi,

In Tripal2, there is a convenient function that the URL "www.mytripal.com/feature/{Gene_ID}" will lead to the search result of this gene record. This is very useful that I could link gene IDs elsewhere to their detail pages in Tripal.

I was wondering that is there similar function in Tripal 3?

Thank you.

Best wishes,

SongtaoGui

**Comment by par12005** [comment]
Hi @songtaogui, thanks for the submission!

This feature may already exist in Tripal 3, but it depends on what you're actually trying to do, and what you mean by the gene ID. [This link](https://treegenesdb.org/gene/121202) goes to a gene in the TreeGenes database. That number, `121202`, in the url is the Tripal Entity ID of that gene, which is different from the gene name, `PSME_00045988`, and is also different from the underlying CHADO record id, `4866182`.

If you are trying to create links and can use the Tripal Entity ID, then you're in luck, because those already exist in Tripal 3! If you are trying to create links programmatically using either of the two latter numbers, I can provide you with some SQL code for queries that should help you determine the Tripal Entity ID based off of a gene name or CHADO record id.

Finally, if you are trying to provide an actual search form for your users, I would recommend looking into the [Tripal ElasticSearch](https://github.com/tripal/tripal_elasticsearch/blob/master/docs/README.md) module. It is a great module with some pretty cool features and you can customize the search form to cater exactly to your needs. Plus you can share replicated search results with a link, such as [this one](http://mimubase.org/tripal_elasticsearch/search_website/?search_box=Migut.D00413.1&op=Search&category=&form_build_id=form-3S5aYH2sZpiJBIaSZAes1BkdwRNI0WO8oIVDZYrCR8w&form_token=6E_L0-QMdDAYac_P6BgTKcaj8Vx9K2AnhMY3_t53VFg&form_id=website_search_box_form) on the Mimubase database.

**Comment by laceysanderson** [comment]
If you did want to link to the gene name (e.g. `PSME_00045988`) in Tripal 3, you can do this by setting the path accordingly. Specifically, by going to Structure > Tripal Content Types > Gene > Edit as shown in the following screenshot:
<img width="1361" alt="Screen Shot 2020-04-02 at 9 04 19 PM" src="https://user-images.githubusercontent.com/1566301/78320257-4aa8b980-7526-11ea-912f-eda8d5e2fcc1.png">


Then you scroll down to the bottom and click on "URL path options". If the gene name `PSME_00045988` is stored in the `[data__identifier]` field (chado.uniquename column) then you would set up the path as follows to `feature/[data__identifier]` and click "Bulk update all aliases".
![Firefox_Screenshot_2020-04-03T03-09-27 773Z](https://user-images.githubusercontent.com/1566301/78320355-7c218500-7526-11ea-85b0-01f721994034.png)

**Comment by par12005** [comment]
That's a great idea, I forgot about this feature! Thanks @laceysanderson!
