### ISSUE TITLE
Integrate the Tripal Daemon module into the core Tripal package

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#103]
We now have a TripalJobs class that is capable of logging all messages.  This makes it easy to spot problems if a job fails.  However jobs need to be converted to use the new Job class to support this.

But, with this functionality, this means we can incorporate the The Tripal Daemon into the core Tripal package.

**Comment by laceysanderson** [comment]
I just merged Tripal Daemon into core :-) It's completely usable at this point but I would like to do the following before marking this closed:
 - [ ] add better integration with the new TripalJob->logmessage()
 - [ ] implement parallel jobs
 - [x] add block to access the log file

**Comment by laceysanderson** [comment]
### Update
- Parallel jobs implemented but still needs configuration built to allow it to be turned on.
- Decided to leave logging up to TripalJob
- Blocks implemented

### Remaining
- Find a way to turn on parallel processing.

This is more difficult then it at first sounds because no drush options from trpjob-daemon are available to the TripalDaemon class (@see drush_invoke_process() in Drush Daemon)...

**Comment by laceysanderson** [comment]
Added a way to turn on parallel processing (72a733810b9e0db3d3f93728b2a90a46f6fb75de) :-D. That makes this task complete 👍
