### ISSUE TITLE
How to override a Dbxref item in tripal3

### ISSUE THREAD

**Issue by songtaogui** [tripal/tripal#1059]
Hi,

I have met a problem while dealing with the dbxref infomation.

For example, if I would like to upload a gff with dbxref information as "**Dbxref=DB1:A_B_C;**", but I mistakenly wroted that information as "**Dbxref=DB1:A,B,C;**". This will lead to a result of:

```
DB1 --> "A"
B --> NA
C --> NA
```

And if I reloaded the correct record "Dbxref=DB1:A_B_C;", the result would be:

```
DB1 --> "A_B_C; A"
B --> NA
C --> NA
```

But all what I what is just:

```
DB1 --> "A_B_C"
```

How to overide the dbxref information while reload a gff file, rather than Incrementally?

Thank you,

Best wishes

SongtaoGui

**Comment by spficklin** [comment]
Hi @songtaogui .  Thanks for pointing out the problem.  It sounds like you can get the correct data into Tripal but cleaning up the incorrect data is where the problem lies.   I tried to provide some instructions for how you can do this and I realized Tripal is missing a few necessary forms to help.  First, we need to add a check in the GFF loader to make sure this doesn't happen again.  Second, we would need a form to allow you to delete a database and all of it's cross-reference entries. This would allow you to remove the B and C entries, for example. Third, we need a form to allow you to remove individual cross references. This would allow you to remove the "DB1:A" entry but leave the "DB1:A_B_C" entry.  

So there are two options for you.  You can either wait until we can add these tools to Tripal.  I don't know how long that will take or you can try to remove these bad entries with a bit of SQL.  Do you feel comfortable using SQL?

**Comment by laceysanderson** [comment]
Just checking in @songtaogui, we have not made any progress in adding the mentioned tools to Tripal although you would be welcome to contribute time permitting. Have you made any progress fixing this issue in your setup?

**Comment by songtaogui** [comment]
@laceysanderson, after a further look of my data, all the incorrect records have only one letter, so we just removed the entries with only one letter in SQL, and re-load.

**Comment by laceysanderson** [comment]
👍 Glad you found a solution!
