### ISSUE TITLE
Provide access to spliced mRNA sequence from feature sequence page.

### ISSUE THREAD

**Issue by mdondrup** [tripal/tripal#108]
And another feature request:

Currently, there doesn't seem to be an easy way to access the spliced mRNA or CDS sequence of a feature of type mRNA, except than splicing the sequence manually guided by exon coloring.

**Comment by spficklin** [comment]
For Tripal v3 we have a CDS field that creates the coding sequence.  It is currently written but is disabled at the moment because it's too slow to to build the CDS on the fly from data in Chado....  

It is possible to also do this in Tripal v2 but would require the creation of a new template and calling the right function.   

We'll get back to this once we finish up with the Tripal v3 release.

**Comment by bradfordcondon** [comment]
done in tripal 2 with #617 but looks like this issue is actually for t3 so leaving open.

**Comment by mdondrup** [comment]
This was solved for 2.x in #617

**Comment by laceysanderson** [comment]
Closing this issue as there is more documentation in the referenced #891
