### ISSUE TITLE
Need help genetic maps and TripalMapViewer

### ISSUE THREAD

**Issue by MoradMokhtar** [tripal/tripal#1081]
Dear, Tripal Team
I want to bulid database for genetic maps for my organism
I want to use Tripal.3 to bliud genetic maps and MapViewer page such as  "https://www.pulsedb.org/mapviewer/691/LG01"
I downloaded Tripal.3 and installed it as mention at user guide "https://tripal.readthedocs.io/en/latest/user_guide.html"
but I don't known how use it to 
1- bulid genetic maps page
2-which table I can use
3- insert maps data
4-view it on webpage
5- genetic maps view pages
can you provide an example for build genetic map and map view
Thanks for your support

**Comment by bradfordcondon** [comment]
Hello

TripalMap is a Tripal extension.  You'll want to follow the instructions there for installing the module and loading data  https://gitlab.com/mainlabwsu/tripal_map
I would suggest posting any questions you have there.

**Comment by laceysanderson** [comment]
Hello @MoradMokhtar,

Regarding general Tripal functionality, I suggest looking at the tutorial: https://tripal.readthedocs.io/en/latest/user_guide/example_genomics.html. This walks you through how to create pages and load genomic-focused data but is important for getting an idea of how to use Tripal/Drupal to manage content in your site.

My general workflow for new content is:
1. Setup your content type (i.e. genetic maps) to ensure the page display, edit form and URL match your preference: https://tripal.readthedocs.io/en/latest/user_guide/content_types.html
2. Find an extension module to load your data (for genetic maps: [MainChadoLoader](https://gitlab.com/mainlabwsu/mcl) or [TripalQTL](https://github.com/uofs-pulse-binfo/tripal_qtl)) and read the documentation to learn how it stores data in Chado (note: both extensions listed store the data the same for genetic maps). 
3. Format your data to match the format required by your chosen importer and follow the instructions for that module to import your data. This loads your data into the needed Chado tables but doesn't yet create pages.
4. Publish your newly loaded data to create pages. Here's an example for how to do this for gene pages: https://tripal.readthedocs.io/en/latest/user_guide/example_genomics/genomes_genes.html#creating-gene-pages. The process is the same for genetic maps except you choose genetic maps from the drop-down instead of genes :-) Don't forget to run the Tripal Job on the command-line.
5. As an administrator you can see your newly created pages under Content > Tripal Content. By default, Tripal creates a "Data Seach" menu (if you don't see this on your site, go to admin > structure > blocks and place the "data search" menu where you can find it) which leads users to your content. There should be one for genetic maps which lists the pages you just created.

As @bradfordcondon mentioned, for questions specific to extensions, ask on their github/gitlab repositories. For general Tripal functionality, you can ask here :-)

**Comment by MoradMokhtar** [comment]
@laceysanderson  and @bradfordcondon 
Thanks for your kind response and your effort. I will do these steps as @laceysanderson mentioned
Regards

**Comment by laceysanderson** [comment]
Hello @MoradMokhtar, just following up -were you able to access the information you needed? Do you have any suggestions for improved documentation for Tripal core?

**Comment by spficklin** [comment]
I'm going to close this out since there's been no response since October. @MoradMokhtar please feel free to respond if you still need support and we can reopen this.
