### ISSUE TITLE
Accessing organism features and chromosomes from the organism page

### ISSUE THREAD

**Issue by shmenolin** [tripal/tripal#1150]
Hello,
I am trying to set up a model organism website with Tripal and currently working with Tripal 3 until the 4 gets released. I have some questions:
1. I loaded the chromosome sequence for an organism but saw that I cannot directly search for the loaded chromosome. How do I search for such features loaded to the database? I can see gene search but not for the chromosome.
2. For a particular organism, can I link its chromosome (loaded to the database) with in the organism page?
3. What would be the best way to see the records stored in the chado database installed through Tripal? I cannot access it through command line terminal

**Comment by spficklin** [comment]
Hi @shmenolin.

By default, Tripal does not provide a chromosome (supercontig) page.  This is because usually there are so many things associated with a chromosome (i.e. huge DNA sequence, genes, variants, etc.) that the page would have too much information and never load.  What kind of information did you want to show on a chromosome page?

However, it is possible to create a chromosomal page, and once you create the pages, Tripal will automatically provide a default search tool for you.   This page will walk you through the steps of creating a new "chromosome" content page:  https://tripal.readthedocs.io/en/latest/user_guide/content_types/creating_content.html
You can skip the parts about "Find a Controlled Vocabulary (CV) Term" and "How to Add a CV Term" because the chromosomal sequences are already assocaited with the term you used when you loaded them into the database using the FASTA loader.

**Comment by shmenolin** [comment]
In an organism page, I wish to have side links that would link me to its chromosome (not necessarily a page, just a point to the sequence file or so) and features and CDSes of the organism. In the Tripal V2 I saw a sidebar named "feature browser" but not in Tripal V3. So how can I do this in Tripal v3?

Also I am unable to figure out how to search for a feature other than gene and mRNA in Tripal V3 because when I go to "find tripal content" I can only search for the following content types:

<img src="https://user-images.githubusercontent.com/61807957/104768492-c84b5800-573b-11eb-97d2-9815957b85dc.png" width="400" height="400">

Not sure how to search for other features

**Comment by spficklin** [comment]
In Tripal v2 we did have a feature browser.  That was actually added in Tripal v1 because organisms tended to only have one genome assembly.  Now, some organisms can have multiple and some assembly features naturally overlapped.  So, we took that out.  

Here's an approach to get you something similar to what you want:
1.  Create an "analysis" content page for each genome assembly. You'll want to describe how the assembly was created, etc.  
2. You can use Drupal's field user interface to add a new field in which you can attach assembly files.  Alternatively, we have a new beta Files module that you can use to attach files (but be warned it's in beta):  https://github.com/tripal/tripal_file.
3. Install the Tripal Manage Analyses module created the by the Staton Lab. It is found here: https://github.com/statonlab/tripal_manage_analyses. It will add to your organism page the list of analyses for that organism which should include your genome assembly.   Users can then get access to all information about the assembly from the analysis page.  

Regarding search forms for features.  Tripal will provide a search form for every content type you have.  By default Tripal only provides a few (gene, mRNA).  If you want more, you have create the content types (using that link I provided in the previous message above).  Once the content type is created, Tripal will provide a search form for the new content type.

**Comment by shmenolin** [comment]
Thank you, the module is very helpful. 
Also, what I wanted was to have a link for existing chromosome for the organism (the one I loaded using chado fasta loader)and features (loaded via chado gff3 loader). Is there any way to do it? And also summarize the features of the organism (I saw the summarizing feature was available in Tripal v2). 
Is there any extension to do it as well? Where can I find out all the available tripal extension modules?

**Comment by laceysanderson** [comment]
We have a community curated list of Tripal Extension modules available on our documentation: https://tripal.readthedocs.io/en/latest/extensions.html

Unfortunately this doesn't include everything available as not every group with a Tripal site adds their modules to this list. I would first check there and if there isn't something to do the job you are looking for I would start an issue asking about it here in case we know and bring it up in the next Tripal users meeting :-)

Regarding the link for chromosomes on an organism page you may need to make a custom Tripal field (well documented) 🤷‍♀️ Hopefully @spficklin will chime in if there is an easier way or existing solution that I don't know about.

**Comment by spficklin** [comment]
> what I wanted was to have a link for existing chromosome for the organism (the one I loaded using chado fasta loader)and features (loaded via chado gff3 loader). 

For this I would recommend following the steps I posted in my previous content.  I think that's the easiest way to get you something akin to what you want. I don't think it would be good to have a "chromosome" page with Tripal.   @laceysanderson provided a good solution if you are comfortable programming and want something custom.  

> And also summarize the features of the organism (I saw the summarizing feature was available in Tripal v2).

This is no longer supported by core Tripal and I'm not aware of an extension module that will do this. This is because most sites don't summarize genomic data by organism, but rather provide summaries by "analyses" or assemblies.

**Comment by spficklin** [comment]
Hi @shmenolin did you have any additional questions on this topic?

**Comment by shmenolin** [comment]
No, thank you very much for your help.

**Comment by spficklin** [comment]
Okay, I'm going to close this out, but if you have further questions on this topic feel free to add another comment and we can reopen it.
