### ISSUE TITLE
Linking custom table to chado base tables

### ISSUE THREAD

**Issue by shmenolin** [tripal/tripal#1182]
I have a question about creating custom table in tripal. So this is the schema I came up with:
```
array (
  'table' => 'isolates_summary',
  'fields' => array (
    'organism_id' => array (
      'type' => 'int',
      'not null' => true,
    ),
    'common_name' => array (
      'type' => 'varchar',
      'length' => '255',
      'not null' => true,
    ),
    'Isolate_name' => array (
      'type' => 'varchar',
      'length' => '255',
      'not null' => true,
    ),
    'rflp_group' => array (
      'type' => 'varchar',
      'length' => '255',
    ),
    'serogroup' => array (
      'type' => 'varchar',
      'length' => '255',
    ),
    'fame_group' => array (
      'type' => 'varchar',
      'length' => '255',
    ),
    'species_by_rflp' => array (
      'type' => 'varchar',
      'length' => '255',
    ),
    'species_by_serology' => array (
      'type' => 'varchar',
      'length' => '255',
    ),
    'species_by_fame' => array (
      'type' => 'varchar',
      'length' => '255',
    ),
    'species_by_16s' => array (
      'type' => 'varchar',
      'length' => '255',
    ),
    'species_by_its' => array (
      'type' => 'varchar',
      'length' => '255',
    ),
    'vlp_production' => array (
      'type' => 'int',
    ),
    'type_id' => array (
      'type' => 'int',
      'not null' => 'true',
    ),
  ),
  'foreign keys' => array (
    'organism' => array (
      'table' => 'organism',
      'columns' => array (
        'organism_id' => 'organism_id',
      ),
    ),
    'cvterm' => array (
      'table' => 'cvterm',
      'columns' => array (
        'type_id' => 'cvterm_id',
      ),
    ),
  ),
)
```
I want to link it to organism base table in tripal, so that when I create views for the organism, I can select the columns from the custom table as well. I have already added all the headers as local cvterms in my database.
What do I need to do further for that? Thank you.

**Comment by laceysanderson** [comment]
In order to integrate with views, the Tripal Chado Views module implements hook_views_data for all chado tables, materialized views and custom tables. With your schema array above, you provided the information that Tripal Chado Views needs to make the connections you want so you should be good to go. **I'm assuming you have Tripal Chado Views installed.**

To add your custom table to an organism view, you will need to set-up the relationship to your custom table. Here is a tutorial for how to do that in Drupal Views UI: https://www.sitepoint.com/relationships-contextual-filters-field-rewriting-views-3-drupal-7/. When you add a relationship using the linked tutorial you should see your custom table name in the options. Once the relationship is added to the view you should see the fields from your custom table available under fields, filters and sort (depending on column type).

**Comment by shmenolin** [comment]
Thank you for your response. I have enabled it but the table is not listed when I try to add a relationship of 'chado organism ' views with this custom table. Is there any other step I am missing?

**Comment by laceysanderson** [comment]
Hmmm... in that case you may have found a bug. I will test this myself and get back to you.

**Comment by shmenolin** [comment]
To add into this thread, I see some custom tables and materialized views I created do not appear in chado integrated tables list and when I try to integrate from "chado views integration", I get the following warning and error:
```
Notice: Undefined index: tripal_views_integration_form in drupal_retrieve_form() (line 809 of /var/www/html/db/includes/form.inc).
Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'tripal_views_integration_form' not found or invalid function name in drupal_retrieve_form() (line 844 of /var/www/html/db/includes/form.inc).
```

**Comment by mario-lopez-c** [comment]
Hi! Did you find a way to relate this? It is because I am trying to do the same, but I am trying to relate the mRNA content type with its family, I have uploaded the family information to a custom table, but I don't know how to show this relation... maybe could you help me? (So, basically I wanna link a gene id and the type of family to which it belongs)

**Comment by shmenolin** [comment]
I could not link the custom table so I added all the properties to organismprop table using type_id => value properties and could link each organism to the required property. A way around for you I guess would be to store the family information in featureprop table then you would be able to link it to mRNA or gene_id.

**Comment by mario-lopez-c** [comment]
@shmenolin great! Thank you so much for the information!

**Comment by mario-lopez-c** [comment]
Hello @shmenolin! I have uploaded the data to the featureprop table relating it with the feature_id of the feature table, which is the one that shows the mRNA content type. But the relationship does not appear, do you know or what did you do to show the relationship on the webpage? How did you publish it? Thank you so much!

**Comment by shmenolin** [comment]
Under manage fields in the mRNA content type, if you click on 'check new fields', you should see the new properties added as fields. Then you can change how to display them under manage display option, most of times they are hidden by default which should be changed

**Comment by mario-lopez-c** [comment]
Thank you! Yes, that works! Thank you so much!

**Comment by mario-lopez-c** [comment]
Hello @shmenolin! Do you know to show synonyms in the mRNA Content-Type? I mean, I have loaded into the synonym table some data and related it to the feature table in feature_synonym table, but I don't know how to publish those synonyms within the mRNA content type, I have only been able to publish the information that is within the featureprop table. 
Thank you!

**Comment by laceysanderson** [comment]
Closing this as a stale issue.
