### ISSUE TITLE
New GFF3 loader issues

### ISSUE THREAD

**Issue by chunhuaicheng** [tripal/tripal#1215]
System information

    Tripal Version: 3.6
    Drupal Version: 7.x
    PostgreSQL Version: 12
    PHP Version: 7.3

The new GFF3 loader loads data much faster which is great. However, our user reports two issues:

1. It does not honor the 'Name' attribute assignment in the GFF3  9th column. After loading the data, both feature.name and feature.uniquename are filled with the same value as the 'ID' attribute in the 9th column.

2. It won't associate features with specified analysis (which is a required field on the form) by inserting  a Chado analysisfeature record.

**Comment by spficklin** [comment]
Hey @chunhuaicheng thanks for reporting it.  Any chance you can look through that code and supply a fix for it?

**Comment by spficklin** [comment]
@chunhuaicheng I just tested the GFF loader and I am not seeing this behavior.   The Name attribute is properly getting added and there are records for the analysis/feature combo in the analysisfeature table.  Can you send me a GFF3 file that is giving you problems so I can test it?

**Comment by spficklin** [comment]
So @jhumann was able to give me an example GFF3 file that was causing problems and now I see what's wrong.  The issue only occurs when landmark sequences are self referencing.     There are three ways to specify a landmark

1. Using the ##sequence-region header at the top of the GFF3 file
2. Setting the sequence type in the GFF3 Tripal loader so that any landmarks are automatically created.
3. Self referencing landmarks where the landmark name (column 1) is the same as the ID in the attributes section.

The GFF3 loader is not handling type #3 and it's not associating the landmarks with the analysis.  We can fix both but it will take a bit of reworking because with the self-referencing style it's possible that a landmark could have other attributes as well and we may need to handle those (e.g. Alias, Dbxref, etc.)

**Comment by srobb1** [comment]
Hello All,

I am seeing the same when I loaded a gff but I am not just missing Name= but also Ontology_term= and Dbxref= as was mentioned above.

In this site we do not want a genome and genome locations. I call these features transcripts since they do not have genes and are not "located" on a genome. My transcripts are my landmark features.

There is an example line: 
```
SMED30035834	smed_20140614	transcript	1	3133	.	.	.	ID=SMED30035834;Name=slc4a-2;Dbxref=GenBank:AKN21408.1,SmedGD GBrowse:SMED30035834;genbank_definition=slc4a-2;ahrd_human_readable_description=Anion exchange protein;Ontology_term=GO:0005452,GO:0006811,GO:0006820,GO:0008509,GO:0015698,GO:0016020,GO:0016021,GO:0098656,PLANA:0000018,PLANA:0000020,PLANA:0000027,PLANA:0000034,PLANA:0000044,PLANA:0000047,PLANA:0000054,PLANA:0000099,PLANA:0000418,PLANA:0002063,PLANA:0002075,PLANA:0003116,PLANA:0007528;
```

In my current and working Tripal 2 site, that I am trying to replicated in T3, I have these same transcripts loaded as src features and have attributes associated with them. Maybe reviewing the T2 gff loader code would help to modify the T3 loader code to load attributes. I can poke around and see what I can find.

Sofia

**Comment by spficklin** [comment]
Hi @chunhuaicheng this has been fixed by a pull request that @srobb1 provided!  (Thank you Sofia!).   The fix is in the dev branch (7.x-3.x) so you should be able to load those sequences now.
