### ISSUE TITLE
Release 3.7 doesn't have the version number updated in any of the files

### ISSUE THREAD

**Issue by dsenalik** [tripal/tripal#1226]
Release 3.7 doesn't have the version number updated in any of the files, e.g.
```tripal/tripal.info:6:version = 7.x-3.6```

**Comment by dsenalik** [comment]
I was just thinking, should the version number be updated just _after_ a release, so the dev version is effectively the next version?

**Comment by spficklin** [comment]
Thanks for reporting this @dsenalik .  I have submitted a pull request to fix the version numbers for the next release to 3.8.  Your idea about setting the next version number right after a release is a good idea.   I'm going to close this out since the PR should fix this for at least the 3.8 version.
