### ISSUE TITLE
YAZ library requirement for AGRICOLA Pub Imports with PHP8

### ISSUE THREAD

**Issue by heh30** [tripal/tripal#1287]
Users who have updated to PHP8.0 are unable to perform AGRICOLA Publication Imports because there is not a corresponding PHP8 release to install yaz with pecl.  Attempting to install yaz results in errors.

https://github.com/indexdata/phpyaz/issues/16

Is there an alternative to YAZ for allowing use of the AGRICOLA importer for systems using PHP8.0+?

**Comment by dsenalik** [comment]
As the last one to work on this importer, I am also wondering if yaz will be updated. I know of no alternative at the moment.

**Comment by dsenalik** [comment]
The current release (from 2018) 1.2.3 does not compile for PHP8. However, the current development version on github works fine with PHP8. Here is the procedure I used to install this and get yaz working again:

1. I'm not sure if you need to uninstall your 7.x version of phpyaz first, but I did this at the beginning:
```sudo pecl uninstall -r yaz```
2. ```git clone https://github.com/indexdata/phpyaz.git```
3. ```cd phpyaz```
4. Probably not necessary, but I "updated" the version number from ```1.2.3``` to ```1.2.3.1``` in three files so that I know things worked. If you choose to do this, edit ```IDMETA```, ```package.xml```, and ```php_yaz.h```
5. Install with
```sudo pecl -d php_suffix=8.0 install package.xml```
6. In the php config file ```/etc/php/8.0/apache2/php.ini``` add the line
```extension=yaz```
7. Restart apache

**Comment by spficklin** [comment]
Thanks @dsenalik for digging into this question, and this is great news.  Looks like a PHP 8 compliant version is on the way and in the meantime there is a work-around.  We should leave this open until we can update our documentation.

**Comment by dsenalik** [comment]
I am closing this issue since with https://github.com/indexdata/phpyaz/pull/17 which created phpyaz release 1.2.4 there is now nothing special or different that needs to be done for PHP8
