### ISSUE TITLE
7.x-3.0-rc1 Add Tripal Content  links to Organism content type

### ISSUE THREAD

**Issue by GreenInnovator** [tripal/tripal#132]
Added an organism, but can't navigate to the Add Tripal Content and click on the link Analysis as Add Tripal Content links directly to Organism content type.

**Comment by spficklin** [comment]
I think the problem is due to the installation problems you encountered in issue #131.  I've seen this behavior when not all of the content types are available.  I think you've got two options:

1) Start over with the installation to ensure the php compatibility issues from the previous steps don't continue to cause other problems for you.

or ...

2)  Try and prepare Chado again by navigating to  Tripal -> Data Storage -> Chado -> Prepare Chado and click the "Preapare this site" again.

**Comment by laceysanderson** [comment]
@uitde007 just checking in to see if @spficklin's suggestions helped? I have also experienced this in the past when errors were encountered during site preparation and re-preparing the site fixed it for me.

**Comment by GreenInnovator** [comment]
1 . Dropped the postgres drupal db and re-installed from there but the "Add Tripal Content" still links directly to the Organism content type.
2. no luck either

**Comment by laceysanderson** [comment]
Hmm. I am still unable to reproduce this behavior. 
1. Can you check Admin Toolbar > Structure > Tripal Content Types (admin/structure/bio_data) to confirm you see all 7 default content types?
2. Try clearing the cache a number of times using `drush cc all` and then try again. If the answer to #1 was yes, this appears to be an issue on Drupal's side where it is not rebuilding the menu system to pick up the new types -clearing the cache should solve it, if this is the problem.

I'm assuming you see no errors when preparing your site? Also can you check the Drupal log for recent errors: Admin Toolbar > Reports > Recent log messages (admin/reports/dblog) and also check the apache error log (location depends on your system).

**Comment by GreenInnovator** [comment]
`druch cc all ` solved it ;Thank you!
