### ISSUE TITLE
GFF3 Loader landmark lookup needs to check type_id

### ISSUE THREAD

**Issue by dsenalik** [tripal/tripal#1324]
### Issue description
In issue #1271 and pull request #1316 we have discovered that the landmark lookup may select the wrong feature if two features share the same `uniquename` and same `organism_id`. The other column of the unique constraint `type_id` is not checked.

#### Steps to reproduce

Currently this does not trigger any kind of error, the first step will be to throw an exception and then work from there. ~~This by itself is enough to get testing to fail.~~

#### Example showing when this is a problem:
Picture two genome assemblies for a single organism. Version 1 has a scaffold with the uniquename chr1 and then version 2 has a pseudomolecule with the uniquename chr1. This type mismatch can happen with different assembly software or just by judgment call if the second assembly chr1 is substantially bigger then the first version. If you imported these two genomes into chado you would end up with two records in the feature table with a uniquename of "chr1" and the same organism. This is allowed because the type_id is also included in the unique constraint.

Now if you have a GFF3 file with a collection of features located on "chr1", a bug would be reached since the importer wouldn't currently know which one to use. It seems like the current code will just throw away one of these "chr1" features and basically just pick one to use without throwing an error.

**Comment by laceysanderson** [comment]
Work has been started on this in #~~1325~~ #1369 with a check throwing an exception. It currently breaks the automated tests showing this is definitely a problem that has gone unnoticed for awhile.

**Comment by dsenalik** [comment]
The problem with automated tests was that I originally implemented the check incorrectly, it always failed.

No matter, it is all fixed now and ready for review.

**Comment by spficklin** [comment]
Hi @dsenalik thanks for trying to tackle this issue, and for posting PR #1369.  Because I've been a bit negligent of the PR queue lately I hadn't noticed what you've done there.  @risharde and I were working on this very same issue in the Tripal v4 GFF3 loader.  So, I'm tagging him here.   This is the solution we came up with for the Tripal v4 loader.


Problems:
----------
1.  The findLandmarks() function has an SQL statement for finding a landmark
    that doesn't include the organism and the landmark type so this may cause
    an accidentally selection of an incorrect landmark, such as on for a 
    completely different species. 
2.  Landmark_type specified in the form currently applies to all landmarks but
    what if a GFF file has different types of landmarks:  chromosome, scaffold,
    contig, etc. Then the landmark_type will incorrectly give all them the same
    type. 
3.  When the landmark type is defined in the GFF file then the loader doesn't
    consider it and the user must specify the landmark type in the form when
    they shouldn't have to.
    
Solutions:
----------
- Rename the $this->landmark_type to $this->default_landmark_type (this is 
  the value coming from the form.  Fix it everywhere it is used. 
- Add a new class variable: $this->landmark_types which is an associative array. 
  The key is the landmark name, and the value is the type name. 
- In the prepareFeature function, when we create the landmark record, set it's
  type in the $this->landmark_types variable.  Use the 
  $this->default_landmark_type unless the ID matches the landmark name then
  use the feature type.
- Edit the findLandmarks() function to update the SQL to use the organism and 
  landmark type.
- Edit the insertLandmark() function to use the landmark type.

Can you change your code in the PR for the Tripal v3 loader to match?  The primary reason is that the type of the landmark can be set in the GFF3 file and we completely ignore that. Your fix in the PR looks good (I haven't fully tested it), but it's also missing this piece.  Maybe @risharde has fixed this already and can just share his code?

**Comment by dsenalik** [comment]
How is "When the landmark type is defined in the GFF file" done @spficklin @risharde ?
I don't see in the gff3 spec how to associate a landmark type with a ```##sequence-region abc 1 234```, maybe I am just missing it.

**Comment by spficklin** [comment]
Landmarks can be included in the GFF File as if they were a feature. The name in the frist column must match the name given to the ID and the start and stop coordinates are the full length of the landmark.  The type of landmark can be different in one file. For example, a genome assembly can have both chromosomal sequences and scaffolds all in one GFF file.  Those types would be given in the type column for the landmarks.  

When we add landmarks that are specified in the GFF3 file we should be sure to use the type specified rather than the one given by the user in the GFF submission form.  That one given in the form should only be used if nothing else can be determined.  

More about that issue is here:  issue #1380

**Comment by dsenalik** [comment]
Okay, thanks for the link, I get that now. We might have to support including ontology name for weird cases like if you had two different cv's containing ```chromosome``` you would have to use ```sequence:chromosome```, or else add an ontology selector to the form (or both!)

**Comment by spficklin** [comment]
I'm not sure I've ever seen that structure used in a GFF3 file before for feature types.  The assumption that we make with Tripal is that all items in the feature table should be using the sequence ontology and I don't recall I've ever found a genomic feature in a GFF3 file that didn't have a term in the sequence ontology.  So, I think we are safe to just use that.   Do you have an example?

**Comment by dsenalik** [comment]
That's true, if we only use one ontology then that is easy. Never mind.

Now, I am wondering if the landmark type specified from the form should override those specified in the gff3 file.
Why? How will the loader distinguish
```
##gff-version 3
chr1_h1 . chromosome 1 339755681 . . . ID=chr1_h1;Name=chr1_h1
chr1_h1 . gene 123 456 . . . ID=gene1;Name=gene1
```
from
```
##gff-version 3
chr1_h1 . gene 123 456 . . . ID=gene1;Name=gene1
```
```gene``` is not the landmark type, we would use the type specified in the loader. Unless we have a list of common ```$hey_this_is_not_a_landmark[]``` types.
I think it's safe to assume either all landmark types are defined in the gff3, or none are, and if you specify a type in the loader then you want that type. But what if it is specified by neither? Don't want a "gene" landmark type... Thoughts?

**Comment by dsenalik** [comment]
What fun! ```insertHeaderLandmark()``` is called in step 3 before we get to our type definition so this won't work right now
```
##gff-version 3
##sequence-region chr1_h1 1 339755681
chr1_h1 . chromosome 1 339755681 . . . ID=chr1_h1;Name=chr1_h1
```

**Comment by dsenalik** [comment]
I am working through this and can handle these cases, but because of the difficulty to accurately detect the chromosome|contig|whatever definitions, I feel we should make this "opt-in" and I propose
![20230215_landmark](https://user-images.githubusercontent.com/8419404/219147808-63298946-d4fc-40c5-a5ed-725a01bbefdf.png)

**Comment by dsenalik** [comment]
I think everything is done, and I added a unit test for this new checkbox, which amazingly seems to have worked.

**Comment by risharde** [comment]
I haven't completed this as yet for Tripal 4 - I was concerned with altering the SQL to do this: "Edit the findLandmarks() function to update the SQL to use the organism and
landmark type."

To do this, my thought process was that one would have to match the landmark_type and organism per landmark - which seems to require multiple SQL statements to query this (even it was combined as one single SQL query) - I'm wondering if this is going to be a problem / performance downgrade. Likely I'll test this by the end of this week after doing the code adjustment and trying to run it on a large GFF file.

**Comment by dsenalik** [comment]
This is all it is in my version
```
    $landmark->setValues([
      'organism_id' => $this->organism_id,
      'uniquename' => $landmark_name,
    ]);
    if ($landmark_type) {
      $landmark->setValue('type_id', $landmark_type->getValue('cvterm_id'));
    }
```
You are correct, this is for every landmark, but the results are cached, and these are all columns in a single table (feature), I don't think it is that much of a problem. It's even possible it is faster as postgres will know to only look at one type_id. I look forward to seeing your test results.
*edit* I think there's a bug here, ```$landmark_type``` is never defined

**Comment by risharde** [comment]
hmmm unless I can see your code, there is no $landmark variable in the Tripal 4 version (but it does use Tripal 3 code base which was upgraded to Tripal 4) findLandmarks() function so I can't rationalize it at the moment (I might be mentally tired tonight)

On my side of code, I see this sql variable holding the SQL which I already altered to use the organism_id

    $sql = "SELECT name, uniquename, feature_id FROM {feature} 
      WHERE uniquename in (:landmarks[]) AND organism_id = :organism_id";

But if we need to query by the actual type_id, then WHERE uniquename in (:landmarks[]) can't be used (I think). It would have to be something like 

    $sql = "SELECT name, uniquename, feature_id FROM {feature} 
      WHERE uniquename = :landmark AND type_id = :type_id AND organism_id = :organism_id";

 And this would need to be done for all landmarks in the landmarks[] array (which is what I was concerned would be a performance downgrade). Also, we'd have to look up the type_id (I didn't investigate if this is cached as yet but worst case scenario is that another class variable holds this OR associative array.
  
![image](https://user-images.githubusercontent.com/33866403/219223129-0becdb73-2890-4cfc-9252-725640e54995.png)

**Comment by risharde** [comment]
Oh I just realised you edited the function findLandmark without the s - I was following Stephen's instructions of which I am editing the function findLandmarks() <-- with the s

I *think* the function you are editing only handles the header? I just looked at the Tripal 3 version and findLandmark (without the s) only gets called in the insertHeaderLandmark function

**Comment by dsenalik** [comment]
You're right, that is just for the header landmark. This is more complicated than I thought, I now see your concern. I'll look into this tomorrow ...

**Comment by risharde** [comment]
Thanks @dsenalik sounds good

**Comment by dsenalik** [comment]
I think it is working as desired now. This time my unit test is included and tests the new functionality, including having landmarks with the same name but different type_id can both be loaded, though this has to be from different gff3 files.

@risharde you will note that I left the sql pretty much unchanged, but added a check for type_id in the resulting query hits. This allows us to have two landmarks with same name, same organism, but different type_id without complicating the query. There will be a tiny bit of extra overhead checking these, but only in cases where there are these landmarks with the same names, probably not very common!

A couple of other changes I made are to not generate a md5 checksum for landmarks, use NULL instead, because ```residues``` is just an empty string. But I was able to add the ```seqlen``` to the landmark feature when that can be extracted from the gff3 file.

New form appearance. (a form validation error is generated if you specify both):
![20230216_landmarks](https://user-images.githubusercontent.com/8419404/219444581-89a71894-7a5e-4543-a80b-0e287ac3db99.png)
