### ISSUE TITLE
tripal_chado api function to look up organism from organism name

### ISSUE THREAD

**Issue by dsenalik** [tripal/tripal#1327]
## Feature Request/Discussion
* This feature does attempt to solve an existing problem with Tripal
* I will do it.
* This feature is Not Urgent

### Description
in ```tripal_chado/api/modules/tripal_chado.phylotree.api.inc``` there are api functions for working with organisms.
```function chado_get_organism_scientific_name()``` looks up an organism's name, I propose an inverse function to look up the organism given this scientific name.

Why? Infraspecific nomenclature! It is hard to do this in straight SQL because the infraspecific type in the organism table is stored as the id of the corresponding cv term, and plus this type may or may not be abbreviated ```subspecies``` or ```subsp.```
There is an api function for dealing with the abbreviation ```chado_unabbreviate_infraspecific_rank()```.

This could be a new api function, but it may be cleaner to incorporate into the existing function ```chado_get_organism()``` which currently supports genus+species but for infraspecific we need a type_id value.
This could be done by adding a new 'scientific_name' option and have special code to take care of the parsing. But I might expose that as a new function so both ways work, let's see...

### Your Specific Use Case
The ```sbo__relationship``` tripal field currently only supports genus+species lookup from the full organism name, and only suporrts infraspecific nomenclature through its ajax callback. With this new api function it would be relatively easy to implement full infraspecific nomenclature support.
This will also be used by the Newick importer, see https://github.com/tripal/tripal/pull/1262#issuecomment-1341547683

### Generally Applicable
This could also be useful to incorporate into data loaders.

**Comment by laceysanderson** [comment]
I agree that this is a worthwhile addition!

We are finding both in core and in extension modules that support for the infraspecific name is not very good at all. This is likely since many module developers do not have that test case in their test databases since it was just added in Chado 1.3.

Having a easy to use function to get the organism_id and/or object based off the full scientific name (genus + species + infra type/name) and making it best practice to use that instead of adding the genus + species hack into our queries would make it a lot easier to ensure this support is consistent and wide-spread.

I like the idea of adding it to `chado_get_organism()` for sure! That said, often we only need the organism_id and `chado_get_organism()` does cause a performance hit so an additional specific function would be useful too.

Many of my extension modules need custom queries to make large datasets performant so a SQL function would be ideal. That way it can be incorporated into any query. I have some experience with this so perhaps we can work on that part together @dsenalik?

**Comment by dsenalik** [comment]
@laceysanderson see what you think about how I implemented this, my SQL, and how I named the new function. I tried to follow the pattern but it got longer ```chado_get_organism_scientific_name()``` -> ```chado_get_organism_id_from_scientific_name()```

I'm still thinking about the implementation of abbreviation lookup, maybe that should be specified in some sort of ```$options```, kind of like ```chado_get_organism()``` does, and not be a default behavior (it's not in the function name!). Then we could add ```common_name``` lookup too, maybe.

**Comment by spficklin** [comment]
Issue resolved with PR #1328

**Comment by dsenalik** [comment]
I will just point out that while this function works great for real organisms, it has a hard time with the type of organisms created with automated testing, because it can't handle a genus with a space in it, such as genus = "Mr. Rolando Nitzsche" and species = "Crystel Champlin". 🤷
