### ISSUE TITLE
7.x.3 Biomaterials migration

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#134]
We are unable to migrate our Biomaterials.  Selecting biomaterials at migration step 2 gives `no data for migration or all have been migrated` (screenshot below).  We have Biomaterials in V2, and they have not been migrated.

We are also not able to add new v3 biomaterials via add tripal content. 

![screen shot 2017-07-26 at 10 36 08 am](https://user-images.githubusercontent.com/7063154/28627075-bd27c69c-71ee-11e7-9363-5f442b368fca.png)

**Comment by laceysanderson** [comment]
Ah yes. You would be unable to since this table is not exposed as a potential base table. This will take a little fixing in core Tripal and some input from your group but it is fixable :-)

Quick Question: If you were creating this Tripal Content Type, would you expect all records in the biomaterial table to be of the same Tripal Content Type? Or do you have types of biomaterials indicated in some manner?

Also, could you confirm that chado.biomaterial is your base table (i.e. each record in that table maps to a page in your Tripal site)?

**Comment by bradfordcondon** [comment]
Hi Lacey,

Thanks for getting back.  Let me preface my response by saying we're still getting our heads around how things will work in Tripal 3...  I actually have lots of questions but I'll keep this discussion to this issue

>Quick Question: If you were creating this Tripal Content Type, would you expect all records in the biomaterial table to be of the same Tripal Content Type? Or do you have types of biomaterials indicated in some manner?

I believe that HWG uses biomaterials only for RNA-seq type records, so in our case I'd definitely expect them to be the same type.  Even if we used it more broadly, I still think it would be one type because all the fields would be the same (source, tissue, geographic location, etc...)


>Also, could you confirm that chado.biomaterial is your base table (i.e. each record in that table maps to a page in your Tripal site)?

Yes this is the case.


--

**Comment by laceysanderson** [comment]
That was my thought as well but I wanted to make sure I wasn't missing something. What is your timeline for migration? I'm quite swamped this week but I could try to get to this next week...

Side Note: Even with all the fields being the same it might be a different type. In my mind there are two ways to determine whether you have more then one Tripal Content Type in a given table. 1) From a biologist perspective, are the data different types (e.g. even though both sequence_variants and genetic_markers have almost all the same fields, they are still conceptually different types). 2) You would like a specialized display for two groups of records in the same table (e.g. if I have both crop and wild organisms, I might want two types since the information displayed would be different.)

In reference to additional questions about Tripal 3 -feel free to ask! We just ask that you create a separate issue (I would label it as "help wanted") :-)

**Comment by bradfordcondon** [comment]
Timeline:  whatever it is, it extends far beyond next week so don't sweat it for now.

**Comment by bradfordcondon** [comment]
Also, when you say Tripal Content Type, you mean Bundle in the new V3 vocabulary right?  [ie this issue?
](https://github.com/tripal/tripal_example/issues/8)  I think the terms are being used interchangeably but want to be sure...

**Comment by laceysanderson** [comment]
Yes, they are interchangeable :-) Have you seen this page: http://tripal.info/node/347?

**Comment by bradfordcondon** [comment]
Yes I've read all the documentation but I can't keep the terms straight in my head yet... hopefully will get easier with use.    Thanks again!

**Comment by bradfordcondon** [comment]
Hi, any word on this?  I'm exploring implementing it myself right now but want to make sure it hasn't already been done.  

Thanks!

**Comment by spficklin** [comment]
Hi @bradfordcondon 

I'm jumping in....  So, to summarize, it sounds like you need: 

1) The ability to associate a biomaterial content type using the biomaterial table of Chado, which isn't showing up in the table dropdown on the add new Tripal Content page...
2) Your biomaterial content types didn't migrate over during your upgrade, most likely due to the same problem.

This shouldn't be hard to fix.  Although I'm not sure why the biomaterial table didn't show up.  I think we can get this resolved for you this week.

How are you planning to implement this on your own?

**Comment by bradfordcondon** [comment]
Hi Stephen!

Your summary sounds about right.

>How are you planning to implement this on your own?

No clue!  I'm working through the migration API to understand whats going on and was hoping I could discover the problem.   I originally thought I would need to add something to the migration ie below, but I can see that tables not explicitly addressed should be migrated if they're in Chado, right? 
 
```
 else if ($table == 'biomaterial') {
        array_push($types, array(
            'vocabulary' => 'NCIT',
            'accession' => 'C70699',
            'term_name' => 'biospecimen',
            'storage_args' => array (
                'data_table' => $table
            )
        ));
    }
```

**Comment by spficklin** [comment]
Okay, I just committed code that will allow you to create a biomaterial content type.  I've also added a new field to support the biosourceprovider_id (local__contact field) and adjusted the obi__organism field to support the 'taxon_id' field of the biomaterial table.   Can you test?  I did not test migration, but now that the table is supported it may work.  @chunhuaicheng can help us further if the migration still does not work.

**Comment by bradfordcondon** [comment]
Thanks to @chunhuaicheng and @spficklin for your help!
