### ISSUE TITLE
Undefined function error in gff loader: Tripal 4

### ISSUE THREAD

**Issue by ejrsimr** [tripal/tripal#1379]
## BUG/ERROR report
When loading a GFF I get an undefined function error if "Start Line Number" field is blank.  Error does not occur if I put "1" in the field.  

### System information
Version: t4d8 docker image

### Issue description
Error: Call to undefined function Drupal\\tripal_chado\\Plugin\\TripalImporter\\form_set_error() in /var/www/drupal9/web/modules/contrib/tripal/tripal_chado/src/Plugin/TripalImporter/GFF3Importer.php on line 506 

#### Steps to reproduce

minimal test gff:

##gff-version 3
chr1_h1	.	chromosome	1	339755681	.	.	.	ID=chr1_h1;Name=chr1_h1
chr2_h1	.	chromosome	1	270168396	.	.	.	ID=chr2_h1;Name=chr2_h1
chr3_h1	.	chromosome	1	133856195	.	.	.	ID=chr3_h1;Name=chr3_h1
chr4_h1	.	chromosome	1	55278592	.	.	.	ID=chr4_h1;Name=chr4_h1

**Comment by laceysanderson** [comment]
Thanks for the issue summary!

Additional info for when we fix this:
- Here's the changelog with code samples: https://www.drupal.org/node/2186135
- This was deprecated in Drupal 8 which is why it's removed now and causing WSOD
- When testing you can trigger this by causing any validation error in the GFF3 importer form

Note: We also realized when troubleshooting this that the "Start Line Number" under "Additional Options" seems to require a entry even though it is optional... @ejrsimr found this bug when he didn't fill out this field. Entering `1` allowed him to submit his GFF3 job.

**Comment by dsenalik** [comment]
The bug of not specifying starting line number is fixed in pull #1305 (Tripal 3, merged) by providing a default of 1.
It is not yet fixed in pull #1459 (Tripal 4), I got the error message
```
Error message
Please provide an integer line number greater than zero.
```

**Comment by risharde** [comment]
Added the minor code to Tripal 4 GFF3 loader V2 for this undefined error. We should be good to go here!

**Comment by laceysanderson** [comment]
Perfect -Thanks @risharde I see it in PR #1459.

**Comment by laceysanderson** [comment]
Error fixed with merged PR
