### ISSUE TITLE
Tripal 4 property field can't handle two properties at the same time

### ISSUE THREAD

**Issue by dsenalik** [tripal/tripal#1398]
### System information

* Tripal Version: tv4α docker container

### Issue description
I'm trying to understand fields, but playing with an existing field is not behaving like I would expect. One property is leaking over into another.

#### Steps to reproduce
1. Create a project to play with
2. Go to ```/admin/structure/bio_data``` and for Project select "Manage Fields"
3. +Add Field
4. Select field type "Chado Property" and label it "Library", "Save and continue"
5. Base table select project
6. Number of values set to Unlimited, "Save field settings"
7. Controlled Vocabulary Term select ```Library (local:library)```, "save settings"
8. Repeat steps 2 through 7, this time use a DIFFERENT cv term, I used "Book" CV term ```Book (TPUB:0000004)```
9. Go to the entity page for the project, and click "Edit"
10. Under "Library" enter "National Ag Library", and Save
11. Now click "Edit" again
12. Under "Book" enter "Harry Potter and the Tripal Daemon", and hit save
13. This is the result. The second property did not save into chado.
![tv4](https://user-images.githubusercontent.com/8419404/214701543-41d7b199-f030-4b2f-b137-1153a7f7a303.png)
14. Edit again and add a second "Book"
![tv4-2](https://user-images.githubusercontent.com/8419404/214702033-70530383-29cd-47cb-9fee-047111363e97.png)

15. Edit again, fix the Book names, and add a second "Library", and save
![tv4-3](https://user-images.githubusercontent.com/8419404/214702065-c9bfa256-28f2-4607-80ae-1dd8beddd345.png)
```
sitedb=> select * from projectprop;
 projectprop_id | project_id | type_id |        value        | rank 
----------------+------------+---------+---------------------+------
              4 |          2 |    2938 | Harry Potter 2      |    1
              5 |          2 |     113 | National Ag Library |    0
              6 |          2 |     113 | Library of Congress |    1
(3 rows)
```

**Comment by dsenalik** [comment]
This is not directly the cause, but something I found.
In ```tripal_chado/src/Plugin/TripalStorage/ChadoStorage.php``` the variable ```$chado_table``` is not defined when processing a join, and gets a value from whatever was processed previously, I think this line needs to be added near line 659:
```
  if ($action == 'join') {
**  $chado_table = $prop_storage_settings['chado_table']; // ** add this line
    $chado_column = $prop_storage_settings['chado_column'];
    $as = array_key_exists('as', $prop_storage_settings) ? $prop_storage_settings['as'] : $chado_column;
    $value = $records[$chado_table][$delta]['fields'][$as];
    ...
```

**Comment by laceysanderson** [comment]
I'm starting work on this in this branch: `tv4g1-issue1398-propertyFieldBug`

**Comment by laceysanderson** [comment]
I was able to confirm @dsenalik's bug on the organism content type with two fields: `fieldprop1` and `fieldprop2` each with it's own unique cvterm. When creating an organism with these two fields and filling in values for both, the view page shows the value for `fieldprop2` for both fields. Looking at the Drupal tables below I see:

```sql
sitedb=# SELECT field_propfield1_record_id, field_propfield1_prop_id, field_propfield1_type_id, field_propfield1_value FROM tripal_entity__field_propfield1;
 field_propfield1_record_id | field_propfield1_prop_id | field_propfield1_type_id | field_propfield1_value 
----------------------------+--------------------------+--------------------------+------------------------
                          1 |                        1 |                        0 | 
(1 row)

sitedb=# SELECT field_propfield2_record_id, field_propfield2_prop_id, field_propfield2_type_id, field_propfield2_value FROM tripal_entity__field_propfield2;
 field_propfield2_record_id | field_propfield2_prop_id | field_propfield2_type_id | field_propfield2_value 
----------------------------+--------------------------+--------------------------+------------------------
                          1 |                        1 |                        0 | 
(1 row)

sitedb=# select * from chado.organismprop;
 organismprop_id | organism_id | type_id | value  | rank 
-----------------+-------------+---------+--------+------
               1 |           1 |    2853 | GROUP1 |    0
(1 row)
```

Notice:

- Only the second property is actually saved to Chado.
- According to Drupal, both fields point to the same chado record (note: [field]_prop_id = 1 for both fields). This is why the display is showing the same value.
- Drupal does not have the value or type_id saved/cached for either field.

**Comment by dsenalik** [comment]
I am trying to understand how fields work but this is confusing me with even just a single property type. But maybe it is the same problem:
1. For "analysis" content type, add a field "Chado Property" and select the same "Book" cv term as I tried earlier
2. Go to edit and add a book "War and Peace". Works as expected.
3. Enter a second book into chado directly
```
insert into analysisprop (analysis_id, type_id, value, rank) values (1, 2938, 'La Divina Commedia', 1);
select * from analysisprop;
 analysisprop_id | analysis_id | type_id |       value        | rank 
-----------------+-------------+---------+--------------------+------
               1 |           1 |    2938 | War and Peace      |    0
               3 |           1 |    2938 | La Divina Commedia |    1
```
4. cache rebuild
5. The second book does not appear. Try entering a third book with the widget and save. Doesn't appear. Note that "War and Peace" used to be analysisprop_id 1 and now it is 4, so that's not good either
```
select * from analysisprop;
 analysisprop_id | analysis_id | type_id |       value        | rank 
-----------------+-------------+---------+--------------------+------
               3 |           1 |    2938 | La Divina Commedia |    1
               4 |           1 |    2938 | War and Peace      |    0

select * from tripal_entity__field_analysis_book;
   bundle   | deleted | entity_id | revision_id | langcode | delta | field_analysis_book_record_id | field_analysis_book_prop_id | field_analysis_book_linker_id | field_analysis_book_value | field_analysis_book_rank | field_analysis_book_type_id 
------------+---------+-----------+-------------+----------+-------+-------------------------------+-----------------------------+-------------------------------+---------------------------+--------------------------+-----------------------------
 bio_data_2 |       0 |         3 |           3 | und      |     0 |                             1 |                           4 |                             0 |                           |                        0 |                           0
```

**Comment by laceysanderson** [comment]
😬  Good to know. I'm greatly expanding the testing on the chado storage class so I'll make sure to capture this as well.

**Comment by laceysanderson** [comment]
I am working on this again 🙃 

Current Summary:

This bug is caused because the default behaviour of ChadoStorage->buildChadoRecords() is to collate all field properties dealing with the same table into the same set of records. This is important behaviour (not a bug!) to ensure that different fields can each handle part of the base record for example and together form a full record in chado. 

Specifically, ChadoStorage->buildChadoRecords() reads all the field property type and values and creates an array of records to be inserted/loaded/updated in chado with the following structure:

```
array[
  TABLENAME => [
    DELTA => [
      'fields' => [
        COLUMN_NAME => VALUE,
      ],
      'conditions' => [
        COLUMN_NAME => VALUES,
      ],
      'delete_if_empty' => [ ],
      'joins' => [ ],
    ],
  ]
]
```

Since the table name is a key in the array it allows for collation of values across fields!

Unfortunately, since the table name is the key, we can't override that behaviour for fields/tables where we don't want to collate across (i.e. property tables).


## Proposed Solution

- Allow field property types to set a table_alias on all property types regardless of action.
- If the table_alias is not set then use the chado table_name --default is the current behaviour.
- Add a 'chado_table' key on the same level as 'fields' and 'conditions' to use when actually building queries.
- Add a mapping to all alias' for a given chado table in the base $build array to ensure we can easily map back.
- Remove the assumption that the key is the chado table name! Alway use the 'chado_table' key in $records instead.

## Places to be careful

- Keep a close eye on the add join functionality as this uses the afore mentioned assumption a lot and is going to be interesting to update.
- Make these changes in all methods which take the $records as a parameter
- The alias needs to be defined by the field and cannot be defined programatically as I don't think it's reliable to guess when records should be combined and when not.
- The alias should include the unique information but not just the field name. In the case of properties, it would be good to include the table name and the type accession.
