### ISSUE TITLE
Extension modules for Tripal 4 

### ISSUE THREAD

**Issue by alslonik** [tripal/tripal#1448]
I wonder whether the extension modules that exist for Tripal3 - for example Tripal Analysis Blast and Tripal Analysis Interpro will be available for Tripal4? I am not a developer, I am mostly a new user of Tripal.  And the question is - whether I  should have installed TRipal3 and not 4 to use all the modules that were written for Tripal3.

**Comment by laceysanderson** [comment]
Hi @alslonik, we're working on that. For extension modules it's the work of those developers to upgrade and not all of them will be upgraded. That said, many are in progress right now. For example, my team is working on Tripal JBrowse, Tripal BLAST and all our extension modules at https://github.com/UofS-Pulse-Binfo/. For other specific extension modules you are interested in, I suggest adding an issue to their GitHub asking if they are upgrading and if so, what they're timeline is.

> Whether I should have installed Tripal3 and not 4 to use all the modules that were written for Tripal3.

Even with that in mind, I would not recommend going with Tripal 3 at this point since it is dependant on Drupal 7 which will no longer be supported in September this year. The upgrade path is still uncertain for Tripal 3 to 4 and I do not want anyone to have to redo work in that short of a timespan. You cannot just stay on Drupal 7 / Tripal 3 because you lose security support.

That said, I do understand the struggle of using Tripal 4 at this point -it's still under active development and not at all ready for site building just yet. If possible, I really suggest holding off on site development for a month or two. I think you will be surprised how much more mature it will be in that short time span as we are all up against the September deadline and very motivated.

**Comment by dsenalik** [comment]
@alslonik I think we answered your question, so I am going to close this, but if you have more questions please reopen it or post a new issue
