### ISSUE TITLE
ChadoStorage changes for records linked through a linker table

### ISSUE THREAD

**Issue by dsenalik** [tripal/tripal#1449]
## Tripal 4 Feature Request
* This feature does attempt to solve an existing problem with Tripal
* This feature is "semi-urgent" 😀

### Description
Sofia and I are working on different tripal 4 fields with something in common: linker tables.
Basically, from the base table (e.g. feature) there is a linker table (e.g. feature_synonym) that links to one **or more** records in another "base table", "linked_table", "object table" or whatever we should call it (in this example the table is synonym).

When adding a record for the field, we need to do two things (in this order): 
1. UPDATE or INSERT a record for the synonym in the chado.synonym table (my field won't have to do this)
2. (DELETE +) INSERT a record in the linker table (feature_synonym) that links feature to synonym.

We each have similar updated versions of ChadoStorage.php  #1447 #1431 (I copied from Sofia😀) but this is not yet working. I'm creating this issue so others know about this and hopefully can make suggestions.

When we have something reasonable to propose, maybe we can make a pull request just for ChadoStorage.php from this issue and all fields can use it?

### More details

We are defining the synonym table with ```store_id``` and two ```store``` actions. We can't use ```store_pkey``` because we need to make sure the synonym is stored before the linker table, and base tables get handled first. What this means is that there are two "base tables" (feature and synonym). Importantly, there can be more than one "base table" record for synonym, whereas for the "real" base table there is only one. Currently ```store_id``` is hardcoded with a delta of ```[0]``` so only the first synonym works.

Updates to follow...

**Comment by dsenalik** [comment]
The current crackpot idea is to introduce a new action ```store_oid``` to store object base table id, along with storing delta values in the base table array.
https://github.com/tripal/tripal/pull/1431/commits/4ce27d5736eb8a48b23b7bf987c4123172a472a2

**Comment by dsenalik** [comment]
Today's suffering involves the fact that two different records might use the same synonym. Like the same gene from two different assemblies. This adds a whole new nightmare of complexity, because we need to check if the synonym we want to insert already exists, otherwise it fails because of the unique constraint. 
I added a ```function selectOrInsertChadoRecord()``` and it does not make me happy, way too complicated, I have to convert fields into conditions, so much could go wrong. Well I'll commit it anyway 💩 https://github.com/tripal/tripal/pull/1431/commits/b9eea9059ebd46e36dd510218f2a29c5fff1801f

**Comment by laceysanderson** [comment]
I'm looking into this now. I have some ideas of how this was meant to work in the design so I'm checking to see if it was implemented that way. If so it might just be a lack of documentation problem and if not I'll see how hard it is to move back to that original design :-)

**Comment by laceysanderson** [comment]
We have had quite a few discussions on this. It had since been confirmed that the current chado storage design does in fact not handle this. After discussions between myself, @dsenalik, @srobb1, and @spficklin we have decided to expand the functionality of the store_link action to support fully describing the join it is supposed to make. The following screenshot shows the new documentation for this (still being developed). I am using the information from Sofia's PR to implement this and add a test showing it works right now. PR coming soon.

![Screenshot of new docs](https://user-images.githubusercontent.com/1566301/226969447-126b15d5-f852-4c61-9f99-e8c19baff75e.png)

**Comment by laceysanderson** [comment]
Update on this. We have decided that we are trying to get ChadoStorage to do too much.

- We will keep the left/right notation documented above.
- **ChadoStorage will not do actual joins but keep the current design where the keys are stored in Chado.** This provides simplicity and a performance boost. To get data added outside the page UI, you will use publish. That's because publish in Tripal 4 is field focused, not entity focused as entities are not tied to a storage backend, only fields are.
- prop-style single-hop fields will continue to work as they have previously
- double-hop linker table style fields will:

    1. Have property types similar to prop-style fields
    2. Property types focus on the linker table only (storing both the left and right IDs
    3. Widgets for these fields are in control of either looking up or creating the record in the right table as needed outside of chado storage
    4. Widgets have a hidden field for the right table id that is populated during form submit once the widget either looks up or created the record


More generally,

- ChadoStorage will support the following cases
    - insert/update columns in the base table (e.g. stock)
    - insert/update columns accessed through a single-hop (e.g. stockprop)
    - select across multiple hops for read-only access
    - read-only access for the base-table (e.g. stock)
- ChadoStorage will NOT:
    - find unpublished records from Chado. For example, if data is imported or pre-existing in chado, then you need to publish first. This will not be done by ChadoStorage.
    - insert/update records in a table accessed through a linker table (e.g. feature => feature_synonym => synonym). In this case the widget will be expected to add/select the synonym record and then add the id to the property. ChadoStorage will manage the feature => feature_synonym part through.
