### ISSUE TITLE
Fix from pull #1433 applies to other fields also

### ISSUE THREAD

**Issue by dsenalik** [tripal/tripal#1466]
# BUG/ERROR report

### Tripal Version: 4.alpha1-dev (today's version)
* Drupal Version: 9.5.4-dev (Tv4 docker)
* PostgreSQL Version: 13.9
* PHP Version: 8.1.16

### Issue description
The problem noted in issue #1432 and fixed in pull #1433 applies to another field, `schema__additional_type`

#### Steps to reproduce
 1. Go to `/admin/structure/bio_data`
 1. For `Biological Sample` select `Manage fields`
 1. `+ Add field`
 1. Select `Chado Type Reference`
 1. For `Label` enter anything
 1. `Save and continue`
 1.  This error is reported:
`Error message
There was a problem creating field BioType: Cannot create a StorageProperty object without a property formatted term:`

**Comment by spficklin** [comment]
As per the comments left on PR #1467 .   The same bit of code that checks if the base_table is set is being used repeatedly in fields. For example:

https://github.com/tripal/tripal/blob/de2d307d7104417effeac069346634f654e56f25/tripal_chado/src/Plugin/Field/FieldType/schema__additional_type.php#L74-L84

This is a good sign that we need a better way to deal with it rather than requiring field developers to add if statements to all their field types.

**Comment by dsenalik** [comment]
For further discussion of this chunk of code see #1469
