### ISSUE TITLE
Switching vocabulary terms of bundles and fields

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#147]
This issue arose working on the Biomaterials migration.  Assuming a goal is to use "correct" ontology terms for most fields and bundles and use less local terms, we would want to switch terms from local to CVs.
Biomaterial, for example, is a term that i think is better described as the [NCIT term Biosample 
C43412](http://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C43412), and indeed the Biomaterial loader is designed to load NCBI Biosamples.

The below approach was suggested by Stephen, but we might want to consider either GUI functionality or some sort of migration code to convert terms.

1.  Make sure the vocabulary name exists in the tripal_vocab table. If not add a new record.
2. Add the term to the tripal_term table (edited)
3. Find the content type in the tripal_bundle table and change the term_id to link to the term you want.
4. Make sure to add the term to the Chado tables too. You can do this using the website at Tripal > Data Loaders > Chado CV Terms and click the "Add term" link (edited)

**Comment by spficklin** [comment]
As an updated... @bradfordcondon (via a slack conversation) resolved to use the term "biological sample" (http://www.ebi.ac.uk/ols/ontologies/sep/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2Fsep_00195).  

Tripal is now updated to create a 'biological sample' content type during preparation so that folks don't accidentally use the local 'biomaterial' term.
