### ISSUE TITLE
Chado is missing constraints?

### ISSUE THREAD

**Issue by carolyncaron** [tripal/tripal#1592]
# BUG/ERROR report

### Tripal Version: The lastest dev version in tripaldocker:latest
<img width="736" alt="Screenshot 2023-07-26 at 4 23 28 PM" src="https://github.com/tripal/tripal/assets/7927760/2d39f0dd-0d36-46ad-92ec-d5a64e769920">

### Issue description

I am using tripaldocker for development of a module, and while testing for duplicate rows in the organism table, I discovered that I can insert the same genus/species combination without any consequence. 

#### Steps to reproduce

To confirm this wasn't an issue with my module, I created a new docker container with just Tripal. Here are the commands I ran:
```
docker run --publish=9000:80 --name=t4 -tid tripalproject/tripaldocker:latest
docker exec t4 service postgresql start
docker exec -it t4 drush sql:cli
sitedb=> SELECT * FROM chado.organism;
sitedb=> INSERT INTO chado.organism (genus, species) VALUES ('Tripalus','databasica');
sitedb=> SELECT * FROM chado.organism;
1 Tripalus databasica 
sitedb=> INSERT INTO chado.organism (genus, species) VALUES ('Tripalus','databasica');
sitedb=> INSERT INTO chado.organism (genus, species) VALUES ('Tripalus','databasica');
sitedb=> SELECT * FROM chado.organism;
1 Tripalus databasica 
2 Tripalus databasica 
3 Tripalus databasica 
```

**Comment by dsenalik** [comment]
With the GUI the duplicate gets flagged
![No-duplicate-allowed](https://github.com/tripal/tripal/assets/8419404/00b208b6-3abb-4bea-9149-98ed31390365)

However I can **confirm this behavior** running the SQL directly.
I thought it to be odd because looking at the table directly: `"organism_c1" UNIQUE CONSTRAINT, btree (genus, species, type_id, infraspecific_name)`

A bit of googling and I found this https://stackoverflow.com/questions/8289100/create-unique-constraint-with-null-columns/8289253#8289253 

It is because both the `infraspecific_name` and `type_id` columns can be NULL.

There are solutions in this link for postgres ≥15 and ≤14 (the docker runs postgres 13.11) but this makes my head hurt.

**Comment by dsenalik** [comment]
Adding the Tripal 3 tag because it happens there too.

**Comment by dsenalik** [comment]
This postgresql 13+ compatible solution seems to work:
```
sitedb=> CREATE UNIQUE INDEX organism_c2 ON chado.organism (genus, species, COALESCE(type_id, 0), COALESCE(infraspecific_name, ''));
CREATE INDEX

sitedb=> insert into organism (genus, species) values ('Tripalus', 'bogusii');
ERROR:  duplicate key value violates unique constraint "organism_c2"
DETAIL:  Key (genus, species, COALESCE(type_id, 0::bigint), COALESCE(infraspecific_name, ''::character varying))=(Tripalus, bogusii, 0, ) already exists.
```

This was mentioned as being an "expensive" option, because the index may be large. On CarrotOmics with 1,884 organisms it is no worse than the original index (there is obviously rounding up going on here):
```
select indexname, pg_size_pretty(pg_relation_size(indexname::regclass)) as size
from pg_indexes
where tablename = 'organism';
   indexname   |  size  
---------------+--------
 organism_c1   | 128 kB
 organism_pkey | 64 kB
 organism_c2   | 128 kB
(3 rows)
```

**Comment by dsenalik** [comment]
So my question is: can or should we fix this? Or is this an issue for Chado itself?
Chado issue: https://github.com/GMOD/Chado/issues/139

Currently we define the constraint for Tripal here:
`tripal_chado/chado_schema/chado-only-1.3.sql:8343:    ADD CONSTRAINT organism_c1 UNIQUE (genus, species, type_id, infraspecific_name);`

MAYBE this could be fixed by changing to
`ADD CONSTRAINT organism_c1 UNIQUE (genus, species, COALESCE(type_id,0), COALESCE(infraspecific_name,''));`

**Comment by carolyncaron** [comment]
Wow, thank you for all of your troubleshooting! I didn't think to check through the interface, but I'm glad to see that it checks for unique values there. Lacey and I were worried this was specific to the Chado instance in the tripaldocker image, but it does seem to be a bug in Chado after all 😛

**Comment by dsenalik** [comment]
Closing our Tripal issue as we can't fix here, this was moved to be a Chado issue with https://github.com/GMOD/Chado/issues/139
