### ISSUE TITLE
Conflicting hook

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#167]
Hello!

I am writing a quick little module to use the [Drupal Relation](https://www.drupal.org/project/relation) module.   The [Tripal Relation Module](https://github.com/bradfordcondon/tripal_relation) finds relation types that are between Tripal Entity and provides support for Chado-linking them to autogenerate relationships.  The result is you get "free" fields from the relation module to display related entities (all the biomaterials for an organism, all the analyses with a biomaterial, etc) if you can link them in Chado.

Unfortunately there is a hook naming problem.  The relation module defines this callback function: 

```
/**
 * Callback to create a relation.
 */
function relation_entity_create($values = array()) {
    $relation = relation_create($values['relation_type'], []);
    foreach ($values as $key => $value) {
      $relation->{$key} = $value;
    }
    return $relation;
}
```

This accidentally hooks into entity_create hook defined in `TripalEntityController`.

What's the best way for me to resolve this?  Maybe the Tripal hook could ignore the relation module?

**Comment by spficklin** [comment]
Hey @bradfordcondon Can you give an example for when you would use the Relation module?  Many of the existing fields handle the relationships in Chado so I was curious what the difference was.

**Comment by bradfordcondon** [comment]
I've got this fear that this module is totally unnecessary.  If so thats OK, it was really quick to make.

I want to list all the...
*  biomaterials derived from an organism at a given organism page.
* analyses involving an organism at a given organism page.
* biomaterials included in an analysis at a given analysis page.

As far as I could tell, the (existing, SIO__relationship) relation field is for things of the same _type_ to get linked to one another (mRNA derived from a gene so feature to feature, biomaterial derived from another biomaterial).  I was basing that on the Chado relation tables.

I thought well, I can create a field for each of these tripal entity types that will display the associated entities.  But then I would be defining a new field every time.  Or I can use the relation module.  I chose the relation module because you can define a relationship between entities, and then that relationship type is an entity, so its available to you as a field.  So instead of having to write a new field each time for every relationship, you create the relationship (as simple as naming it and clicking on the associated entity types), and my tripal relation module will keep those relation types populated based on the CHADO SQL you provide.

If that isn't clear (it doesnt look very clear to me!) let me reverse the question.  What existing field would you suggest I use to list all the biomaterials that are involved in a particular analysis, for example?

Would be excited to demo the current functionality for you and you can tell me if it could be helpful or easier to use existing Tripal fields.

**Comment by bradfordcondon** [comment]
Hi @spficklin 
I had the urge to use this module again so thought I'd ask to think about it again.

- Our old site had a libraries tab on organism
- Libraries are converted as entities (BAC and Genomic libraries +), but to get them to be listed on organisms we'd have to create a new field
- My tripal_relation module would allow libraries to be linked and displayed on the organism page with no additional work

I'd define the relationship between libraries and organisms (a library belongs to an organism, an organism has libraries), input a Chado query that would fetch all libraries given an organism, and I'd be done.  (all admin level, no coding)

You said Tripal already handles this, if so, how?

Thanks!

**Comment by spficklin** [comment]
Hi @bradfordcondon.

You are right in that "relationships" in Chado are mapped through [base]_relationship tables and those relationships typically refer to records within the same table.   What you're describing are relationships but these falls within the "linker" category: i.e. two different types of records being associated with one another.  

Tripal can handle these if a linker table exists (e.g. organism_library) and if a Tripal field exists to query the linker table and share the data on the entity.  By default Tripal has fields already for these linker tables: [base]_contact, [base]_dbxref, [base]_cvterm,  [base]_pub, [base]_relationship, [base]_synonym.

We're missing linkers for libraries and biomaterials and analysis.  In some cases there are no linker tables in Chado (e.g. mapping analyses to organisms).   So, these types of tables have to be added as custom tables.  Then, as long as we have fields that recognize the linker tables then all is good. 

Creating relations between entities with the Drupal Relation module sounds promising and easy but you would end up storing data about biological data in your Drupal tables rather than in Chado.  Is this what you want?  If you ever want to dump your Chado database to share it with others, you'd be missing those relationships because they'd be in some Drupal tables.  

Another thing you miss by not creating a Tripal field is inconsistency in data provided on your site pages and data provided by Tripal Web Services.  It's not clear to me how the Drupal Relation fields will show up in web services.  But even so, the user  will have limited or no access to the data via the relationship.

You are certainly free to do what's best for your site and easiest for you.  But these are just some things to consider.  If you do decide to go down the route of creating new TripalField classes for your linker relationships we'd be happy to consider including those for existing Chado linker tables in the tripal_chado module.

**Comment by bradfordcondon** [comment]
Hi Stephen,
Thanks for your response on this.  To be honest I wasn't aware of the linker tables.  It sounds like the advantage I gain with ease of implementation is lost by storing the data outside of Tripal.  
I'll try implementing the relationships this way.
