### ISSUE TITLE
Increase of PHP memory to help upload larger FASTA files like scaffolds and genomes

### ISSUE THREAD

**Issue by pdtouch** [tripal/tripal#1749]
Currently, large FASTA files are not able to be uploaded e.g. scaffold/genome FASTA files during Gene upload in Tripal v4. The example file size is 6MB

`grep -i max_filesize /usr/local/etc/php/php.ini`

shows a setting of 

`upload_max_filesize = 2M`

If this value can be changed to higher value, it could help with elimination of the current message:

Unfortunately, you can not upload this file as the size exceeds the the maximum file size allowed by this site: 2.1MB. You can manage the maximum file upload size by changing the upload_max_filesize in your php.ini file.

**Comment by dsenalik** [comment]
This is a very good point, if we are providing an "impossible" example.
1. 2M is the same default as Tripal 3. In this day and age and typical computing power, I would be in favor of increasing the default, maybe to 8M?
Big data files are a much more common thing than "back in my day".
2. I would be in favor of having the full path to the `php.ini` file in that message (I for sure never remember it)
HOWEVER that may be difficult. I recently discovered that the max memory setting in a Tripal 4 docker is in `/usr/local/etc/php/conf.d/docker-php-memlimit.ini` instead of `/usr/local/etc/php/php.ini`
Just look at all of the Tripal 3 ini files parsed:
![20240112_phpini](https://github.com/tripal/tripal/assets/8419404/11387be7-3c08-4f83-ad1a-3afbdc27081c)

**Comment by laceysanderson** [comment]
I agree with 8M, maybe 10M at most as we want to keep Tripal requirements as low as possible. You could also add a build arg to the dockerfiles to allow this to be changed during building if people want to test large files.

**Comment by pdtouch** [comment]
Changes requested in docker files:
```
tripal/tripaldocker/Dockerfile-php8.1-pgsql13
tripal/tripaldocker/Dockerfile-php8.2-pgsql13
tripal/tripaldocker/Dockerfile-php8.3-pgsql13
```
to increase file_upload_size to 8MB.

**Comment by laceysanderson** [comment]
Fixed by merged PR
