### ISSUE TITLE
SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 3072 bytes

### ISSUE THREAD

**Issue by webfaqtory** [tripal/tripal#1757]
### Tripal Version

4.0 Alpha2

### Drupal Version

10.2.1

### PostgreSQL Version

14.10

### PHP Version

8.1.27

### General Description

When issuing 'drush en tripal' I get:
SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 3072 bytes: CREATE TABLE "tripal_collection" (
  "collection_id" INT unsigned NOT NULL auto_increment,
  "collection_name" VARCHAR(1024) NOT NULL,
  "description" TEXT NULL DEFAULT NULL,
  "uid" INT NOT NULL COMMENT 'The user Id of the person who created the collection.',
  "create_date" INT NOT NULL COMMENT 'UNIX integer start time',
  PRIMARY KEY ("collection_id"),
  UNIQUE KEY "user_collection" ("uid", "collection_name"),
  INDEX "uid" ("uid")
  ) ENGINE = InnoDB DEFAULT CHARACTER SET utf8mb4; Array
  (
  )

### Steps to reproduce

This is a clean installation of D10.1.2
composer require 'drupal/tripal:^4.0@alpha'
drush en tripal

### Error messages

```shell
SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 3072 bytes: CREATE TABLE "tripal_collection" (
  "collection_id" INT unsigned NOT NULL auto_increment,
  "collection_name" VARCHAR(1024) NOT NULL,
  "description" TEXT NULL DEFAULT NULL,
  "uid" INT NOT NULL COMMENT 'The user Id of the person who created the collection.',
  "create_date" INT NOT NULL COMMENT 'UNIX integer start time',
  PRIMARY KEY ("collection_id"),
  UNIQUE KEY "user_collection" ("uid", "collection_name"),
  INDEX "uid" ("uid")
  ) ENGINE = InnoDB DEFAULT CHARACTER SET utf8mb4; Array
  (
  )
```

**Comment by laceysanderson** [comment]
Good morning, I'm sorry you ran into an error trying to install the new release! I can't replicate this locally and it's not happening in the docker build of the automated testing either.

### Can you provide more information about your environment?

- Are you installing Tripal the traditional way, directly on a server or are you using docker or some other visualization software?
- Do you also have MySQL installed on that machine?

### Possible solution to try

I specifically ask about MySQL because to my knowledge, PostgreSQL does not specify storage engine in that way, although MySQL does. When you install Drupal through the UI, at the database stage it does assume MySQL if you have that as an option. To install with PostgreSQL, you want to ensure that the "Database Type" of "PostgreSQL" is selected as shown here:

![](https://tripaldoc.readthedocs.io/en/latest/_images/traditional.2.install_step_4.png)

That option only shows if you have your server set up to Drupal requirements for PostgreSQL . This includes the typical connection modules between php and PostgreSQL as well as the [`pg_trgm` module shown here](https://www.drupal.org/docs/getting-started/system-requirements/database-server-requirements#s-enabling-pg-trgm).

**Comment by webfaqtory** [comment]
Thanks for your reply,

Sorry it's been a while. I forgot to install into PostgreSQL

**Comment by laceysanderson** [comment]
Ah, so my suspicion that you are using MySQL is correct. The Chado schema requires PostgreSQL so we haven't tested on MySQL at all and the error you are getting is MySQL specific as PostgreSQL supports much longer column names.


**Do you have a specific need to run a Tripal site using MySQL rather than PostgreSQL?**

As far as working to solve this issue:
The problem is specifically that the collection_name column is VARCHAR(1024) and MySQL is known for not supporting large varchar column sizes. We can specify MySQL specific column data types to get around this but then there is the chance that the application might try to insert names that are longer than supported by MySQL.

The tripal_collection table focuses on support for ID Space and Vocabulary Names. We use that size because that is what is the size of the cvterm.name and db.name columns in Chado. While we can override the sizes in Tripal, you will have a lot of difficulty installing Chado in MySQL.

**Comment by webfaqtory** [comment]
All good now. Thanks

**Comment by laceysanderson** [comment]
Awesome! Glad I was able to help :-)
