### ISSUE TITLE
Remove uniqueness constraint on Analysis Program+version?

### ISSUE THREAD

**Issue by mdondrup** [tripal/tripal#1827]
### Tripal Version

4.x HEAD

### Drupal Version

10.2.4

### PostgreSQL Version

15.6 (Debian 15.6-0+deb12u1)

### PHP Version

8.2.7

### General Description

It is not possible two create multiple analyses with the same Program version. Given that parameters and processing could be different, I don't think this constraint makes much sense. In my understanding, "Analysis" refers to an instance or application of a software tool, not the tool itself.  Also, the error message is incomplete.

### Steps to reproduce

Create two analyses with the same software and version.

### Error messages

```shell
Error message
The item cannot be saved as another already exists with the following values. Program: ''. Programversion: ''.
```

**Comment by dsenalik** [comment]
I agree that the constraint on Analysis is odd and confusing. It is actually the combination of three values: `program + programversion + sourcename`
This is not defined by Tripal, by rather by chado https://laceysanderson.github.io/chado-docs/tables/analysis.html
I don't know the historical reasons for this, but I usually try to populate the "Data Source Name" with publication DOI or something, to avoid just the difficulty you are seeing.
If you feel inclined, the place to post this issue would then be https://github.com/GMOD/Chado/issues.

The error message is the same problem posted in issue #1826, however you might ask why "Data Source Name" is not included, how else would you know that? I'll see if we can fix that too.

**Comment by dsenalik** [comment]
Here's an idea, we could put those three fields in a fieldset box with an informative label
![2024-03-23_analysis-unique](https://github.com/tripal/tripal/assets/8419404/8bee5464-6155-4f48-aa7a-d5299fd0e451)

**Comment by laceysanderson** [comment]
I also dislike this constraint and would support you posting about it on the Chado repo @mdondrup.

@dsenalik I agree that we need to fix this so that the data source is included in the message and I love the addition of the fieldset to make this more intuitive! We can't currently do that using Tripal Layout so we would need to use the Field Group API directly. The logic for doing this on the display is in [TripalEntityUILayoutController](https://github.com/tripal/tripal/blob/4.x/tripal_layout/src/Controller/TripalEntityUILayoutController.php). I think it would be similar for acting on the form except we would need to figure out how to get the form equivalent of the EntityViewDisplay object 🤔

**Comment by dsenalik** [comment]
Pull request #1855 will be adding a bit of text to better explain the constraint, so now you will be told which three columns make up the unique constraint.

**Comment by laceysanderson** [comment]
I'm closing this issue as PR #1855 ensures that users are now told the three fields making up the unique constraint in the error message. This resolves the confusion that this issue was born out of. The further issue regarding how much sense the analysis table unique constraint makes should be opened up on the Chado repository.
