### ISSUE TITLE
Annotations field failing to load

### ISSUE THREAD

**Issue by almasaeed2010** [tripal/tripal#193]
Hi,

The sio__annotations field is causing the following errors in our site.

```
Warning: key() expects parameter 1 to be array, null given in sio__annotation->load() (line 243 of /tripal/tripal_chado/includes/TripalFields/sio__annotation/sio__annotation.inc).
Warning: array_key_exists() expects parameter 2 to be array, null given in sio__annotation->load() (line 249 of /tripal/tripal_chado/includes/TripalFields/sio__annotation/sio__annotation.inc).
Warning: array_key_exists() expects parameter 2 to be array, null given in sio__annotation->load() (line 252 of /tripal/tripal_chado/includes/TripalFields/sio__annotation/sio__annotation.inc).
Error: Cannot access empty property in sio__annotation->load() (line 261 of /tripal/tripal_chado/includes/TripalFields/sio__annotation/sio__annotation.inc).
```

Thanks!

**Comment by spficklin** [comment]
Can you tell me what content type you are getting this error?

**Comment by almasaeed2010** [comment]
It happened immediately after enabling the field on the "manage display" tab on any feature type. Specifically, it happened on mRNA and Gene entity types. 

Oddly, the error caused the entire site to stop working except for the administration pages.

Thanks!

**Comment by spficklin** [comment]
So, the error is caused when the sio__annotation load() function is called.  This is only called when a page first loads data from the database.  Thereafter, field data is cached.   The problem seems to be that the feature_cvterm table is not being returned by the chado_get_schema() function.    So, if you have a site-wide problem other than with the administration pages then I don't think this is the problem but perhaps a symptom of a different problem.  Do you have any other messages in your Drupal report logs?

**Comment by almasaeed2010** [comment]
What's posted above are all the error messages the we got.

Would the result of the field get cached if a fatal error gets thrown in the `load()` function?

**Comment by almasaeed2010** [comment]
I think this problem was caused by a php cache issue in our end (OPCache). Once I restarted OPCache and enabled the field, it worked without any errors! So I am gonna assume this a cache issue not related tripal.

Thanks!
