### ISSUE TITLE
Title URL is long and not unique when creating a custom content type.

### ISSUE THREAD

**Issue by laceysanderson** [tripal/tripal#2009]
### Tripal Version

4.x

### General Description

When you create a new content type through the UI, Tripal assigns a default URL and Title template. However, there are not any fields for this content type yet, so the title format ends up being a combination of tokens referring to the content type WHICH IS NOT UNIQUE. This format is just quietly provided with to warning to the user 🙈 

### Steps to reproduce

1. Go to Admin > Structure > Tripal Content Types > Add Custom Type.
2. Fill in a name and term but more importantly, scroll down to the Title section and confirm that the title suggested includes only tokens with "TripalEntityType__" at the beginning. This means that all the titles for content of this type will be the same!

### Error messages

This was missed for so long because it does not provide an error... but it will cause issues with duplicate titles.

### Screenshots

![image](https://github.com/user-attachments/assets/59d0ee22-c374-4350-b188-6f06f53237e5)

**Comment by dsenalik** [comment]
Because of the order that things happen, the site admin will need to manually create a title format once the needed fields have been added.
Some crackpot ideas:
Idea 1. Make a token for the entity ID number (the number not the name) - this would guarantee uniqueness, and be always present.
Idea 2. Have a blank title format, and validate when you try to make the first entity, if you have not populated it gives a message. Not sure I like this though. And would have to validate for publish too.
Idea 3. Default title is some fixed text like "Title format has not been specified - you need to do that". Again I don't much like this, plus the non-unique title persists.

**Comment by laceysanderson** [comment]
> Idea 1. Make a token for the entity ID number (the number not the name) - this would guarantee uniqueness, and be always present.

We actually have this: `[TripalEntity__entity_id]` but we don't allow it for titles -only for URLS 🙈 that's caused by that 'include id' option: the option is TRUE for url pattern and FALSE for title pattern.

We could also add a drupal set message warning that tells the user the title pattern is not ideal due to lack of fields and instructs them to add fields and then come back here to set the title pattern.

I do worry this would be forgotten and the titles would be aweful with no one knowing how to fix them... maybe we have a check in setTitle() that confirms the title pattern contains field tokens? And if not, warns the admin that they can configure better titles by going to LINK ;-p

Note: the tokens in TripalEntity have a property that indicates if this is a field token or not. We could use this to determine if the default pattern hits on this bug and should be updated.

**Comment by dsenalik** [comment]
When PR #2040 is merged, the default fallback title format will be
  `$format = 'Entity [TripalEntity__entity_id]';`
so the uniqueness problem will be solved. The ugliness problem will not.
The remaining task now for this issue is to finish @lacey's idea of a warning that you forgot to set a proper title format.
This warning should happen in two places, adding a new entity through the UI, and during publish.
