### ISSUE TITLE
API to create organism, analysis, ...

### ISSUE THREAD

**Issue by abretaud** [tripal/tripal#202]
Hi,
I'm working on porting python-tripal to tripal3. I need to create new organisms (or analysis, ...) using the API.
With tripal2, I was using the Services module which exposed CRUD methods for nodes.
Now that organisms are no longer nodes in tripal3, I wonder how to create them programmatically.

Is there in the Tripal code a magic function like tripal_add_organism which would create the entity and populate the chado table? If not, what's the easiest way?

(I've started implementing in tripal_ws some code to catch POST HTTP request and use the posted json array to create entities. We could create a new organism like this:
```
curl -X POST -H "Content-Type: application/json" -d '{"genus":"Mygenus", "species":"somespecies", "common_name":"Cool org", "description": "blablabla <br> test"}' http://localhost:8500/tripal/web-services/content/v0.1/Organism/
```
What do you think about it? I can also implement it in tripal_rest_api module if you prefer)

**Comment by shawnawsu** [comment]
HI @abretaud ,

Just so I understand, you're asking about creating new organisms (entity) when the organism content type (bundle) already exists?

If you are looking to do entities have you looked at using the tripal.importer.api? That will load your info then you could use the tripal.entities.api to load them. 

Thanks,
Shawna

**Comment by abretaud** [comment]
Hi

> Just so I understand, you're asking about creating new organisms (entity) when the organism content type (bundle) already exists?

Yes that's it!

> If you are looking to do entities have you looked at using the tripal.importer.api? That will load your info then you could use the tripal.entities.api to load them.

Yes I know about the new importer mechanism, I use it now for loading fasta, gff, blast, interpro and go.
I didn't want (but maybe I'm wrong!) to use it for organism-like entities because I was looking for a more lightweight way to create them, without creating a job.
I've looked at tripal.entities.api but it's not clear to me how I can use it :/

Anthony

**Comment by spficklin** [comment]
Hi Anthony,

This is a very good question.  There is currently no API function to create organisms programatically.  We need to do this.  Technically, you can do this now by creating an entity object programmatically.   For this you create a new entity instance and as long as you add the fields with appropriate values you can save the entity and the Tripal code will try to do the insert. It will work as long as you setup the entity object correctly.  If you want to try to explore this route I can share with you some code examples.  

However, the challenge is knowing what fields are available for a given entity.  Tripal v3 allows a site to add any number of fields, hide non-wanted fields, and store fields in locations other than Chado.  So, if you wanted to make some generic Python wrappers to insert organisms you would have to be aware of which fields the site has, what values each field supports, and which ones are required.

We have two approaches we can do for this.
1)  We can create an API function that returns this information in JSON. You can parse the JSON to determine what fields are available and provide that list to the user who will use your Python code.  
2)  We use the Hydra WC3 vocabulary with Linked-data RESTful webservices to make all Tripal content available.  This is a self-discoverable approach and it comes with a Hydra JSON-LD method that describes the entities and fields similar to what I just described in option #1.  You could pull from web services to get the information needed to setup the insert via web services rather than through command-line integration with the PHP API.

Ideally, I think we could provide both approaches. I think the first may be more useful to you.  Let me know what you think of either of these solutions and we can work towards getting you what you need.

**Comment by abretaud** [comment]
> This is a very good question. There is currently no API function to create organisms programatically. We need to do this. Technically, you can do this now by creating an entity object programmatically. For this you create a new entity instance and as long as you add the fields with appropriate values you can save the entity and the Tripal code will try to do the insert. It will work as long as you setup the entity object correctly. If you want to try to explore this route I can share with you some code examples.

Sounds good, as a first solution your code examples would be very useful!

>However, the challenge is knowing what fields are available for a given entity. Tripal v3 allows a site to add any number of fields, hide non-wanted fields, and store fields in locations other than Chado. So, if you wanted to make some generic Python wrappers to insert organisms you would have to be aware of which fields the site has, what values each field supports, and which ones are required.

Yes, for the moment I'm mainly interested in creating entities with "standard" fields, like organisms, just to make python-tripal "Just Work" with tripal3 the same way as it works with tripal2.
I'd like also to discover available entity types and corresponding fields, but this is less urgent for me at the moment.

I think I can make my python code directly parse the json-ld content if we choose your approach #2. Is it already implemented or not? (I've seen http://localhost:8500/tripal/web-services/vocab/ service, but not sure where to look in this service)

**Comment by spficklin** [comment]
@abretaud In response to the question you posted on pull request (issue #211).   I have added some additional elements to the arrays provided by the elementInfo().  Each element now will include: 'required' (can be true/false), 'readonly' if when during create/update operations the field cannot be set, and 'type' to indicate the type of field.  The type field uses the XSD Schema Types (e.g. xs:string, xs:integer, etc.).   

I have also started a few functions that will morph into an API for creating entities.  The one I currently have working is a function you can use to get the details about any content type.  This will return to you an array that should provide the information you need to know how to insert a new record.  Can you look it over and see if there's anything you can think of that this array doesn't handle that you'll need?  

I've committed the code to a new branch:  7.x-3.x-entity-crud-api.    You can take a look at the array by running this drush command:

`drush php-eval "print_r(tripal_get_bundle_details('bio_data_1'))"
`
on my site 'bio_data_1' is the organism content type.

**Comment by spficklin** [comment]
Okay, so I closed out pull request #211 because I handled the POST for web services a bit differently.  Here's what I did:

1)  I added a new API function named tripal_insert_entity().   This function is meant to be used for creating a new entity.  You pass it the bundle name (e.g. bio_data_1) and an array of field values.  The field values array is an associative array. See the function's documentation for more details.
2)  I renamed the TripalWebService::handleRequest to be TripalWebServices::handleGET, and I added corresponding functions for POST, PATCH and DELETE.  
3) The TripalField class now has a new prepValues() function.  This allows you to provide only the values you want and the field will work out all of those 'chado-xxxx' items that need to be added for a proper insert/update.  This means you only need to worry about providing values as indicated by the array returned by the tripal_get_bundle_details() function.
4) This new code is in the 7.x-3.x-entity-crud-api branch.

The web services POST does not yet work.  I have made a note in that function to reformat the params provided by the user to fit the array wanted by the tripal_insert_entity() function which it should call, but I have not yet written that code.  However, the API function currently works for non complex fields.  Those are fields that only take a single value.  There is a code sample you can follow in the header for that function.  But you can test on the command-line with this drush command which adds a new organism:

`drush php-eval "\$entity = tripal_insert_entity('bio_data_1', array('taxrank__species' => 'Eucalyptus',  'taxrank__genus' => 'baueriana',  'local:abbreviation' => 'E. baueriana',  'common_name' => 'Werribee blue box',  'schema__description' => 'E. baueriana subsp. thalassina is a subspecies of Eucalyptus baueriana that is endemic to Victoria. It was first formally described by taxonomist Kevin Rule in Muelleria in 2011',  'local__lineage' => 'cellular organisms; Eukaryota; Viridiplantae; Streptophyta; Streptophytina; Embryophyta; Tracheophyta; Euphyllophyta; Spermatophyta; Magnoliophyta; Mesangiospermae; eudicotyledons; Gunneridae; Pentapetalae; rosids; malvids; Myrtales; Myrtaceae; Myrtoideae; Eucalypteae; Eucalyptus'));"  --user=1`

I think this will get you much closer to what you wanted.  We still need to add in support for those more complicated fields. To do that we need to add prepValues() functions to those fields to make them work.

**Comment by abretaud** [comment]
Thanks for your work! It looks much cleaner like this

The array produced by `tripal_get_bundle_details()` looks great. Where could we expose the result of this function in the REST API?

`tripal_insert_entity()` looks great too!

I've made #229 to fix a few warnings I found while testing.
I'm not sure https://github.com/tripal/tripal/pull/229/commits/786f6b7eab559c53fb0d20df24add41b828720b1 is the best fix for empty name

**Comment by spficklin** [comment]
The web services use the W3C Hydra vocabulary to make it discoverable.  Part of that discoverability is the API documentation which is provided in JSON for a client application.  You can see what that looks like on our demo site at this link: 

http://demo.tripal.info/3.x/web-services/vocab/v0.1

Each content type has a "Class" stanza in the returned JSON will all of the fields listed as properties.  It's not 100% ready, but if you take a look at it I think you'll be able to see how it's working.

**Comment by abretaud** [comment]
Was there some progress made on this?
I have pushed the original python code I wrote in december to work with entities in https://github.com/galaxy-genome-annotation/python-tripal/pull/1, I'm wondering if it's something I can try to finish before the new python-tripal release, or if I should wait for the tripal code to be ready

**Comment by spficklin** [comment]
Hi @abretaud unfortunately, there has been no progress on this front.

**Comment by spficklin** [comment]
@abretaud .  This is a bit of an old issue.  We definitely need this capability, but I'm curious if you are still working on this, or expecting a fix, or if you have worked around it?

**Comment by abretaud** [comment]
I think that's still something that would be useful, but I'm not actively working on it. Currently python-tripal is able to create organism and analysis entities, even if the [fields are hard coded](https://github.com/galaxy-genome-annotation/python-tripal/blob/master/tripal/organism/__init__.py#L122)

**Comment by spficklin** [comment]
Okay, I'll add this to be worked on for a v3.3 release.  Hopefully we'll be able to work on it!

**Comment by laceysanderson** [comment]
There has still been no progress made on this front and development focus is moving to Tripal 4. Since @abretaud has a work around for python-tripal I'm going to close the issue. That said, if anyone would like to collaborate on adding this functionality, we would be happy to work with you!
