### ISSUE TITLE
Boolean search as an editable view or block

### ISSUE THREAD

**Issue by risharde** [tripal/tripal#235]
Is there a way to edit the 'view' that returns results when using the find/publications boolean search feature? Need to customize the search results and add other filters to it. Not sure this is possible or if this would fall under a feature request

**Comment by spficklin** [comment]
Apologies for the slow reply.  The end of the year is a bit overly busy!  

The find/publication tool was added in Tripal v2 because we could not get Drupal Views to provide a very good search tool for publications.  The Chado pub table that stores publications is a bit problematic in that some properties are built into the table while others are expected to go in the pubprop table.  With Tripal v3 it's much easier to make a publication search, but still the find/publication provides a bit more functionality.  However, because it is a coded in PHP (not defined in Drupal Views) changing it is a bit difficult. 

What kind of filters do you want to add and how do you want to change results?

**Comment by spficklin** [comment]
This has sat in the queue with no further comment for a while. I'm closing, but @risharde if you need any additional input/help with this please comment.
