### ISSUE TITLE
Cannot display field using Manage Displays for custom Chado data

### ISSUE THREAD

**Issue by risharde** [tripal/tripal#236]
Hi Stephen, experiencing an issue I cannot wrap my head to resolve. It is regarding the Contact Tripal Content Type. I'm seeing the field 'Topic of Interest' which is tied to what seems to be a custom cvterm name known as 'topic of interest'. The term was added to the field settings via the manage field area. On the manage display, I have made this field visible. Unfortunately, it's not displaying any output and I also see an error at the top of the page which says:

Notice: Trying to get property of non-object in chado_linker__prop->load() (line 81 of /var/www/Drupal/sites/all/modules/tripal/tripal_chado/includes/TripalFields/chado_linker__prop/chado_linker__prop.inc).

Any ideas?

**Comment by risharde** [comment]
Was able to get the data to show, apparently it was the wrong display (default). Had to select Full content. However the error message still shows up on the page so still maybe a small 'bug'

**Comment by almasaeed2010** [comment]
@bradfordcondon is traveling today but I think he  almost understands this issue

**Comment by risharde** [comment]
@almasaeed2010 Thanks for the info!

**Comment by bradfordcondon** [comment]
Did you create the topic of interest field as a chado property for your bundle?  Or Tripal did?

 I imagine you have a contactprop set with the cvterm = topic of interest for one of your contacts.  Is that right?  The problem is that you don't have a matching Cvterm for topic of interest.
This is the line that is giving the error:
`    $cvterm_id = $cvterm->cvterm_id;`

I would first double check that you have a cvterm with the CV = `local` and the name = topic of interest (matching the field name)

**Comment by spficklin** [comment]
The code on line 81 of the chado_linker__prop:load() function is trying to get the CV term from the database.  It's failing to get it and causing this error.  Are you sure you have the CV term set for the field and that the CV term is in the database?

**Comment by shawnawsu** [comment]
@risharde indicated in #305 that this issue is resolved.
