### ISSUE TITLE
Regular expressions for parsing BLAST XML file

### ISSUE THREAD

**Issue by btski** [tripal/tripal#284]
### System information

* Tripal Version: 3
* Drupal Version: 7.56
* PostgreSQL Version: 9.5.10
* PHP Version: 7.0.22-0ubuntu0.16.04.1
* Server: AWS cloud instance

### Issue description

I've been trying to get the BLAST module to work with demo sweet orange data. Figured out how to get SwissProt BLAST setup properly, but I'm struggling with NCBInr BLAST. Regular expressions were not provided, and my attempts to write regex have not been going well. My main concern is getting valid name/accession so I can hyperlink to GenBank. This is my current NCBInr BLAST page:
<img width="839" alt="screen shot 2018-02-07 at 6 30 27 pm" src="https://user-images.githubusercontent.com/32686196/35949026-1d46676e-0c35-11e8-8d34-fa4ef9e03728.png">

Note that the values are not actually accessions and fail to link to the appropriate page. Based on the given regex for SwissProt, I've been trying to extract data exclusively from regions contained by <Hit_def> tags. Other XML tags would work better, but attempts to write expressions corresponding to other tags have failed (presumably if a regular expression fails to find a match in any instance, it will revert all searches to a generic expression). I'm unsure if the failure is due to non-matching or disallowed tags. The matching criteria is also very strange, requiring the entire line be matched and making things more difficult.

Any clarification on how the regular expression is interpreted in this situation is welcome. Working regular expressions for Hit Name/Accession that fit the [demo file](http://www.gmod.org/mediawiki/images/2/24/Blastx_citrus_sinensis-orange1.1g015632m.g.fasta.0_vs_nr.out) would also be very much appreciated. My current regular expression for Hit Name/Accession is ".*?\|.*?\|.*?\|(.*)\|\s.*?]"

[Explanation on how to setup BLAST module](http://tripal.info/node/130)

**Comment by btski** [comment]
Assuming the NCBI test file is consistent with the corresponding BLAST XML format, I'll probably parse new files with Python to include all desired fields within the <Hit_def> tag. I'm fairly certain you cannot specify XML tags via regular expression. Not sure if the program defaults to- or exclusively reads from the <Hit def> tag.

**Comment by spficklin** [comment]
Hi @btski .  Have you tried checking the 'Use Genbank Style Parser' when you setup the NCBI nr database?   When BLAST encounters an NCBI formatted FASTA file it parses the definition line automatically and there is no need for regular expressions.  The Tripal BLAST parser can pull the relevant data from the XML instead.  If you have tried that and it's not working then perhaps there's a bug and we need to look into it.

**Comment by btski** [comment]
I forgot to mention I've tested the NCBI style parser. When "Use Genbank Style Parser" is selected, the output corresponding to the test file is strange.

<img width="849" alt="screen shot 2018-02-14 at 1 12 32 pm" src="https://user-images.githubusercontent.com/32686196/36223315-a2795f1e-1189-11e8-864f-dd00c573b0bd.png">

The visual looks to be correctly formatted, but parsing for the graph seems to have failed. Overall, it's better than anything I've managed with regular expressions alone. Perhaps it is the test file that's in error. I haven't yet tried using my own files/data.

Edit - Despite the match name being the unedited contents of the <Hit_id> tag, the hyperlink correctly directs to the proper page. The description also isn't being parsed, containing all contents of the <Hit_def> tag. Is this behavior intended?

**Comment by spficklin** [comment]
Yes, this is the current behavior of the code.  The entire hit_def is not shown (there are ellipses at the end) in order to keep the table small with each row being one line only.  The idea is that the user gets enough potential information about the hit and can see more if they click the [more] link.

For the hit name, we just use the hit_id as BLAST provided it with the thought that BLAST indicated that was the full hit name so we should preserve it.  

However, I see your point that it does look a bit odd.  I think what you're suggesting is that you would have expected the hit name to just be the accession (e.g. XP_002302784.1) and the hit description to be the full text.   Is this right?

**Comment by btski** [comment]
That would have been my expectation. It almost appears as though an attempt to parse was made, but the line format was inconsistent across the file. I've noticed that if a regular expression is used that doesn't conform to all lines available, it will fail and default to an output that includes all contents of the target line. For example, if you attempted to parse the following two lines up to ">"...

GSK-like kinase [Aegilops tauschii] >gi|109290442|gb|ABG29427.1| GSK-like kinase 1 [Aegilops tauschii]
GSK-like kinase 1D [Triticum aestivum]

It would likely fail, as the second line does not have the ">" character. Not only does the first line look odd, it contains redundant information.

I can fix these issues by parsing the XML file itself now that I know it's intended behavior. Or leave it as is, since it's a minor problem.

**Comment by spficklin** [comment]
I think this can be an easy adjustment and it makes sense.  But let me bring in a few other folks to get their opinion before we make a change.  @laceysanderson @ekcannon @mestato @bradfordcondon @guignonv @childers @srobb1 @mpoelchau @abretaud

Are there any objections if we change the Genbank style parser to parse the hit name to just include the 4th element with the '|' as the seperator.  So gi|109290442|gb|ABG29427.1| becomes ABG29427.1.  And if we include the full definition in the results rather than just the a line ending with an ellipses?

**Comment by mpoelchau** [comment]
@spficklin - my main concern would be that the GenBank defline format (and RefSeq) seems to have changed since NCBI deprecated GI numbers.

https://ncbi.github.io/cxx-toolkit/pages/ch_demo#ch_demo.T5

GenBank fasta defline format now seems to be gb\|accession\|locus instead of gi\|GInumber\|gb\|accession

**Comment by laceysanderson** [comment]
I think this issue should be moved to https://github.com/tripal/tripal_analysis_blast. Was any progress made on it?

**Comment by srobb1** [comment]
@spficklin  Sorry for chiming in so late. If you are still looking for input, I am okay with just the accession 'gb\|([^|]+)' being used and having a longer def line. I am also okay with the current shorter definition.

@laceysanderson tripal_analysis_blast does seem like the best place for this issue.

**Comment by bradfordcondon** [comment]
sorry for never chiming in.

Whatever makes the linkout work IMO.  I dont think the average user of our site is going to care which genbank accession iD is displayed.  @mpoelchau 's concern is a good one.

I'm creating the analysis_blast issue since yes that is where discussion belongs.
