### ISSUE TITLE
Enabling tripal_chado Module Throws an Exception

### ISSUE THREAD

**Issue by almasaeed2010** [tripal/tripal#31]
Hello,

When upgrading from Tripal v2 to v3-beta3 I got this error during installation of tripal_chado.
However, running the command a second time doesn't throw any errors and executes successfully.

```sh
$drush en tripal_chado

DatabaseSchemaObjectExistsException: Table cache_image already    [error]
in /data/www/html/drupal-7.54/includes/database/schema.inc:660
Stack trace:
#0
/data/www/html/drupal-7.54/includes/database/database.inc(2776):
DatabaseSchema->createTable('cache_image', Array)
#1
/data/www/html/drupal-7.54/includes/common.inc(7114):
db_create_table('cache_image', Array)
#2
/data/www/html/drupal-7.54/includes/module.inc(479):
drupal_install_schema('image')
#3 phar:///bin/drush/commands/core/drupal/environment_7.inc(143):
module_enable(Array)
#4 phar:///bin/drush/commands/pm/pm.drush.inc(1167):
drush_module_enable(Array)
#5 phar:///bin/drush/includes/command.inc(422):
drush_pm_enable('tripal_chado')
#6 phar:///bin/drush/includes/command.inc(231):
_drush_invoke_hooks(Array, Array)
#7 phar:///bin/drush/includes/command.inc(199):
drush_command('tripal_chado')
#8 phar:///bin/drush/lib/Drush/Boot/BaseBoot.php(67):
drush_dispatch(Array)
#9 phar:///bin/drush/includes/preflight.inc(66):
Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#10 phar:///bin/drush/includes/startup.inc(458): drush_main()
#11 phar:///bin/drush/includes/startup.inc(365):
drush_run_main(false, '/', 'Phar detected. ...')
#12 phar:///bin/drush/drush(114): drush_startup(Array)
#13 /bin/drush(10): require('phar:///bin/dru...')
#14 {main}
```

**Comment by spficklin** [comment]
This error seems to be occurring when the Image module is enabled.  The Image module is a dependency of the tripal_chado module.   The error seems to indicate a failure when trying to create the 'cache_image' table.  The message seems to be truncated but it looks like it's indicating that the 'cache_image' table already exists when it's trying to create it.  I've seen this type of behavior before when a module is not properly uninstalled.  If you are upgrading from an older database I wonder if the image module may been installed previously, was somehow uninstalled but during the uninstall the cache_image table failed to be removed.  So that this time, when the Image module got re-enabled it had issues because the table already exists.... Just an idea.  I've not seen this error before when installing Tripal v3.

**Comment by almasaeed2010** [comment]
I agree with you. This happened to me before with other modules but I couldn't understand why. Thanks for the explanation!
