### ISSUE TITLE
Tripal rapid install failing.

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#318]
### System information

* Tripal Version:  3.x
* Drupal Version:  7.56
* PostgreSQL Version:  10.2
* PHP Version: 7.2.3
* OS Version: Ubuntu 18.04 (pre-release)

### Issue description
During install I get the following errors:
```
Installing Chado.
Which version of Chado would you like installed?
count(): Parameter must be an array or an object that implements Countable Table.php:789                                                        [warning]
count(): Parameter must be an array or an object that implements Countable Table.php:789                                                        [warning]
count(): Parameter must be an array or an object that implements Countable Table.php:789                                                        [warning]
count(): Parameter must be an array or an object that implements Countable Table.php:789                                                        [warning]
 [0]  :  Cancel              
 [1]  :  Install Chado v1.3  
 [2]  :  Install Chado v1.2  
 [3]  :  Install Chado v1.11
1
WD php: Error: Call to undefined function tripal_add_job() in tripal_chado_load_drush_submit() (line 197 of                                     [error]
/var/www/html/sites/all/modules/tripal/tripal_chado/includes/tripal_chado.install.inc).
Error: Call to undefined function tripal_add_job() in tripal_chado_load_drush_submit() (line 197 of /var/www/html/sites/all/modules/tripal/tripal_chado/includes/tripal_chado.install.inc).
Drush command terminated abnormally due to an unrecoverable error.                                                                              [error]
Use of undefined constant administrator - assumed 'administrator' (this will throw an Error in a future version of PHP) core.drush.inc(1122) :  [warning]
eval()'d code:1

2018-03-23 14:16:49
Tripal Job Launcher
Running as user 'administrator'
-------------------
WD php: Error: Call to undefined function tripal_launch_job() in drush_tripal_trp_run_jobs_install() (line 191 of                               [error]
/var/www/html/sites/all/modules/tripal/tripal/tripal.drush.inc).
Cannot modify header information - headers already sent by (output started at                                                                   [warning]
/home/ficklin/.config/composer/vendor/drush/drush/includes/output.inc:40) bootstrap.inc:1486
Drush command terminated abnormally due to an unrecoverable error.                                                                              [error]
Error: Call to undefined function tripal_launch_job() in drush_tripal_trp_run_jobs_install() (line 191 of /var/www/html/sites/all/modules/tripal/tripal/tripal.drush.inc).
```
I'm installing on a brand new Ubuntu 18.04 pre-release setup. I'm not sure if this issue is related to the ne OS or recent changes we've made in the code.

**Comment by spficklin** [comment]
@bradfordcondon how hard would it be to add the rapid install to our current installation unit tests?

**Comment by bradfordcondon** [comment]
doesn't the rapid install clone a specific release?  Doesnt this just tell you that rc-2 doesn't install properly (which we already knew?), and adding it to the test would just tell you the build status at the state of the release?

Anyway if its worth doing, not hard at all.  Just spin an extra docker container from the drupal base, same as the tripal install.  But change the build process to follow the rapid install procedure instead.

edit: looking over quick install...a couple of problems...

* interactive commands. i dont know that this works with travis (you are supposed to set it to non-interatctive mode...)
* Would need to start from a different container since it sets up drupal for you, and our test container starts at  Drupal being set up.

**Comment by almasaeed2010** [comment]
I'd suggest keeping the tests out of the main tripal and adding it to the rapid install repo itself. Since the installer pulls a specific tripal version, the build process will be auto triggered on travis every time you change that version. I'd also suggest not using docker for this one and implementing a travis environment, which gives us the advantage of testing a tripal install on multiple php and PostgreSQL versions (a good way to ensure tripal is working properly on different environments without slowing down CI on the main repo) . If that sounds good to you guys, we can submit a pull request pretty easily.

**Comment by bradfordcondon** [comment]
I'm inclined to agree with Abdullah here.  Trigger a new build on the rapid install repo with every new release candidate.

**Comment by almasaeed2010** [comment]
Hello,

I've added travis integration to the tripal_install repo in this PR: https://github.com/tripal/tripal_install/pull/3

The PR supports matrix testing so the command will get tested against all of php 7.x versions automatically once enabled.

Thanks!

**Comment by shawnawsu** [comment]
I did some testing of rapid install in ubuntu 16.04 and on Mac OS and everything works as expected, so I believe it's your php/ubuntu/drush version. Did you get a site up and running and are the tripal drush commands working?

**Comment by spficklin** [comment]
Just following up to see if the issue is resolved?

**Comment by bradfordcondon** [comment]
Looks to me like unmerged PR on the tripal install profiles adding CI
https://github.com/tripal/tripal_install/pull/3

**Comment by spficklin** [comment]
This is old. We've worked on the rapid installer. I think it's working. But comment if not.
