### ISSUE TITLE
Drupal.org git sync

### ISSUE THREAD

**Issue by abretaud** [tripal/tripal#331]
INSTRUCTIONS: The following template is meant to provide the information that will help other Tripal developers diagnose and reproduce your issue. Follow the directions below to complete the template. If the template is not appropriate for your issue you may remove it and describe your issue.

### System information

* Tripal Version: 3.x
* Drupal Version: 7.58
* PostgreSQL Version: 9.5
* PHP Version: 7.2

### Issue description

Hi, I'm working on the [tripal 3 docker image](https://github.com/erasche/docker-tripal/tree/v3.x), and preparing a [new python-tripal release](https://github.com/galaxy-genome-annotation/python-tripal/pull/1)
In the Dockerfile, tripal is install with `drush pm-download/enable tripal-7.x-3.x-dev`, but it seems like the [code on drupal.org](https://www.drupal.org/node/1337878/commits) is not synced with the code on github. 
Currently, the docker image is broken because of a bug that I think was fixed in https://github.com/tripal/tripal/commit/abfa405e633e28c46b31668fad0b1f27c7a161d0
Would it be possible to sync the drupal.org git repo? Or maybe I should just clone the github rather than using drush?

**Comment by laceysanderson** [comment]
I just updated drupal.org so hopefully there is a new dev release soon. That said, since all active development occurs over here, I would recommend cloning git if you want to ensure you have the most recent dev version...

I'm going to close this issue as I have updated drupal.org but if for some reason you don't see a new release (they're created nightly) or if you feel cloning through github is not ideal, feel free to re-open.
