### ISSUE TITLE
site does not redirect properly when deleting field?

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#363]
* Tripal Version: 3

We've noticed this on both our dev and personal instances.  When you delete a field, you are not redirected to the bundle page.  Instead the request hangs.  Howeevr, if you manually navigate back to the bundle page, the field has been deleted.  Probably a Drupal thing?  Anyone else noticed this/ is there anything to be done about it?

To make my problem clear:

http://localhost:8083/admin/structure/bio_data/manage/bio_data_1/fields/local__genome_browser/delete

![screen shot 2018-05-04 at 9 59 17 am](https://user-images.githubusercontent.com/7063154/39632012-e2ee05aa-4f81-11e8-8c7b-c66f24d5bd6c.png)

click delete: now we're waiting for host for a long time.

However, if I click on the breadcrumb to go back a page, the field has been deleted.

**Comment by spficklin** [comment]
@bradfordcondon I don't have this issue. I'm able to delete fields no problem and it takes me back to the content type "manage fields" page.  When your process hangs can you see what processes are going on in the database?

**Comment by bradfordcondon** [comment]
no suspicious db activity.  maybe @almasaeed2010  can comment more.  I think it just runs a long string of transactions.  He also cant reproduce on his local machine.

Messing with a field today caused me to delete/re-add many times and I think the problem is snowballing on my local site, everything has ground to a halt and i need to delete the site and rebuild.

**Comment by bradfordcondon** [comment]
the drush command `drush field-delete local__cmap_viewer` is almost instant.  Anyone in the same position as me can use the drush command instead.
Still i wondeer if something curious is going on in my site...

**Comment by isumoc** [comment]
I have the same problem.

Fields don't get deleted immediately - they get flagged for deletion.  Via the web form a call is made to field_purge_batch whereas via the drush command this probably does not get called.

https://api.drupal.org/api/drupal/modules%21field%21field.crud.inc/function/field_purge_batch/7.x

It will be a problem if you try to run cron because the field cronjob will hang.

On my system the call to field_purge_batch infinitely calls field_attach_load and will eventually crash the DB.     

https://api.drupal.org/api/drupal/modules%21field%21field.attach.inc/function/field_attach_load/7.x

To see if this is your issue try 
$ drush eval "field_purge_batch(1)"

Or see if cron will run without issue.

If either of these hang then we probably have the same problem.  I have to shut down postgresql and apache after attempting to delete fields.

**Comment by bradfordcondon** [comment]
Thank you @isumoc !
yes, `drush eval field_purge_batch(1)`does hang for me.  Forgive me if i dont run until my db crashes....
Looks like the same issue.    Sounds like for now we need to delete our fields via drush to be safe.  

Can also confirm on unaffected sites this command does not hang...

Still left wondering if this is a tripal or drupal problem.

**Comment by isumoc** [comment]
@spficklin 

https://drive.google.com/file/d/1WZ9KRlo0aLJia403ui053kbnZBhvsWbC/view   ( ~ 31MB )

I've uploaded a 1 minute log from my dev postgresql box here in csv format.  It appears to do about 100K SQL SELECT statements in that time ( captured from clicking confirm delete until I shut down my apache server ).  Is that the expected behaviour ?  Any insight here would be appreciated.

**Comment by bradfordcondon** [comment]
fixed by PR.
