### ISSUE TITLE
Looking for views fasta export

### ISSUE THREAD

**Issue by mdondrup** [tripal/tripal#376]
Hi,
I am looking for the views data exporter extension that was available in Tripal 1.x. (see the link for api documentation) This allowed to format a data export from a drupal view as FASTA formatted file, with various fields in the header, and attach an export button to the Feature View.  Are there any plans to make this available again? 

http://tripal.info/sites/default/files/tripal_v1.1_api/d7/d11/views-data-export-fasta-footer_8tpl_8php.html

Cheers,
Michael

### System information

* Tripal Version: >= 2.1
* Drupal Version: 7.x
* PostgreSQL Version: 9.5
* PHP Version: 7.1

**Comment by bradfordcondon** [comment]
Hello,

I'm not familiar with Tripal 1.x, but this sounds similar to Tripal collections. [We have this on HWG](https://www.hardwoodgenomics.org/tripal_elasticsearch/search_website/?search_box=transporter&op=Search&category=&form_build_id=form-jRE8c-9mHBvxAmhZHutvv5cPM-yRAJIV8XuEgFyv3ig&form_token=gdtFzL_zoB9sqfY9SWELKso7FI0X4pZaJ9UEbpgmkqI&form_id=website_search_box_form), if you're signed in you can save your search as a collection, which will allow you to, among other things, download the selected items as a FASTA formatted file, with whatever fields you want in the header.

**Comment by laceysanderson** [comment]
Hi Michael,

Currently there are no plans to create a FASTA extension for views data export. The reason for this is a general departure from using views data export in general. This is due to the speed of download which is a huge problem for larger datasets as well as the overhead. Furthermore, views data export is no longer being maintained.

As @bradfordcondon mentioned, Tripal Collections now offers a FASTA file export. However, this is only available as of Tripal 3 and I see you're still using Tripal 2. Are you planning to upgrade to Tripal 3 soon?

**Comment by mdondrup** [comment]
Hi and sorry for the delayed response,

we have plans to migrate to Tripal 3 within 2018 and will start testing soon... However, I would prefer the function available in the form of an export button below the search form for reasons of simplicity. I am sure the collections are useful and flexible but I am a bit concerned about ease of use, they might be a bit complex for our users.

In the meantime I have built an intermediate solution, possibly this is useful for someone:

- Made a derivative of views_data_export https://github.com/mdondrup/views_data_export/tree/7.x-3.x-licebase
Mainly exchanges the Buttons and adds 'FASTA friendly' export, that is an export style with FASTA button and outputting one field per line without any decoration.
- Generated a Data_export in Tripal's Views using an invisible field feature_id, and a Global:PHP field with the code given below. 
- Using the batched exporter takes a while for >10.000 seqs but the number of sequences to export can probably be limited using the Pager option in Views.

Result is here: https://licebase.org/?q=chado/feature

I would like to add that views_data_export is not un-maintained afaik according to https://www.drupal.org/project/views_data_export, they are seeking co-maintainers but have a stable 7.x branch covered by the security advisory policy, and a pre-release for D8.   

Please let me know if you want me to export the full views code.

```
<?php 
  $feature = array(feature_id => $row->feature_id);
  $seqs = tripal_get_feature_sequences($feature, array(derive_from_parent=>0, aggregate=>1, 
  is_html=>0, width=>60));
  if (empty($seqs[0]['residues'])) {
    $seqs = tripal_get_feature_sequences($feature, array(derive_from_parent=>1, aggregate=>1, 
    is_html=>0, width=>60));
  }
  if (empty($seqs[0]['residues'])) {
    $seqs = tripal_get_feature_sequences($feature, array(derive_from_parent=>1, aggregate=>0, 
    is_html=>0, width=>60));
  }
  print ('>' . $seqs[0]['defline']) . "\n";
  print ($seqs[0]['residues']);
?>



```

**Comment by laceysanderson** [comment]
Hi @mdondrup, thanks for the updating and sharing the module you created :-) I'm glad that you have a solution for yourself and truly appreciate you sharing it here for others who may need it!

I'm going to close this issue since you have a solution and the options are documented here for others. However, if you have more to say or if this solution is not a good long term one for some reason, feel free to re-open!
