### ISSUE TITLE
Tripal BLAST UI  undefined variable db_file_id

### ISSUE THREAD

**Issue by oklonova** [tripal/tripal#414]
* Tripal Version: 7-2.1
* Drupal Version: 7.59
* Tripal BLAST UI 7-1.3

Hi,

I have installed BLAST UI module and followed the instructions in the README file: installed NCBI BLAST+, downloaded a database from NCBI using update_blastdb.pl script, and added it as a node to blast against, proving the path. 
The path to the ncbi-blast+/bin is added in the settings. 

The NCBI BLAST+ is at /home/user/ncbi-blast-2.7.1+ (I am having a test Tripal web site running locally).
The database is in sites/default/files/blastdb.

Whenever I want to use this module, I get the following message:

"Notice: Undefined variable: db_file_id in blast_ui_per_blast_program_form() (line 254 of /var/www/html/sites/all/modules/tripal_blast/includes/blast_ui.form_per_program.inc)",
even if I am just checking the box to show an example sequence and upload a fasta file to blast against (without using any database).

Does this have anything to do with the placement of the NCBI and the database files? 

I also wonder how I can blast against my local Tripal/Chado database (provide this option in the list of databases that appear under "Select a Dataset" button).

Any help or hint would be very much appreciated.

**Comment by bradfordcondon** [comment]
This issue is actually a tripal_blast issue, so it should be posted in the [tripal_blast](https://github.com/tripal/tripal_blast/issues) repository.  I copied this issue, its [available here](https://github.com/tripal/tripal_blast/issues/36).  I'm answering the issue in both places for your convenience, but If you have further questions please ask them there.

>I also wonder how I can blast against my local Tripal/Chado database (provide this option in the list of databases that appear under "Select a Dataset" button).

You need to create a blast db node for each database.  You can do this at content -> add Content -> blast database.

>Notice: Undefined variable: db_file_id in blast_ui_per_blast_program_form

I'd bet this error will go away when you add a blast database?  I don't actually see this variable get set so maybe it requires a minor fix, we'll find out.

**Comment by ekcannon** [comment]
@oklonova are you trying to upload a target database or selecting the "Blast database" node you created from the target dropdown? Could you provide a screenshot of the error and form state?
