### ISSUE TITLE
Querying chado database

### ISSUE THREAD

**Issue by oklonova** [tripal/tripal#493]
Hi,

how can we correctly query the chado database from the views that come with Tripal (organism search/ feature search)? 

For example, in the organism search view users are supposed to filter features by organism and have an option to export them to a file. I have features' unique names (and ids which are hidden fields), and some data about organisms, like genus, species, domain, etc. I need to get a list of features in a text file (using Views Data Export module), and modify the template accordingly, to return uniquenames, seqlen, etc. While simply having a list of names is easy, fasta file is trickier. To have all these items in the fields in the view would mean to load too much data which would probably never be used, so it is less space- and time-consuming to load them only when they are needed in a file. 

Here begins the tricky part. Since on the organism page the 'node' is the organism, we cannot use Drupal's node_load() to get all info about features. To use chado_expand_var() to include all info about features into the organism table, would require minimum 3 steps (1.get organism nodes from node_load(), 2.expand the organism table with the feature table, 3.get the necessary information about the features). Can we just do it with a single db query? (we know features ids)

This one produces errors:
$records = db_query("SELECT chado_feature.seqlen, chado_feature.residues FROM {chado_feature} feature WHERE chado_feature.feature_id IN (:nids)", array(':nids' => $nodes))->fetchAll(); 
// $nodes is an array of features nids

I was trying to figure it out from the output of dpq($view->build_info['query']), but this does not seem to help. 
Could you please correct me if my logic or the query is wrong (or both)?

I also wonder what is the general way to query chado database from other modules in Drupal 7.
Tripal 7x-2.1
Chado 1.3

**Comment by chunhuaicheng** [comment]
Hi,
If you're looking for some function that allows filtering and downloading sequences like this page:
https://www.vaccinium.org/search/features
You can try our [Mainlab Chado Search](https://github.com/tripal/chado_search) module.

**Comment by btski** [comment]
The Mainlab Chado Search module documentation will probably benefit me later. Thanks for sharing. 

If I'm understanding @oklonova's question correctly, you're trying to create a query based on the page content (organism name). The organism name is extracted from the page and inserted into the query. Does your query work by substituting a valid organism name into the query? You can test directly through command line:

psql DBNAME USERNAME
password
query
\q (to exit)

Demonstration:
`SELECT seqlen FROM chado.feature WHERE organism_id = (SELECT organism_id FROM chado.organism WHERE abbreviation = 'PRRSV');`

Notes:
My search path is not automatically set to Chado, hence my use of chado.TABLE
Dropped residues call (for testing purposes) because it's clunky to view all available residues on a single page.
PRRSV is an organism unique to my work. Replace it as necessary.
Assigning table names ({chado_feature} feature) is not necessary when calling from a single table. I'm not sure if your name assignment is valid. Try this instead:
`SELECT chado_feature.seqlen FROM chado.feature chado_feature WHERE organism_id = (SELECT chado_organism.organism_id FROM chado.organism chado_organism WHERE abbreviation = 'PRRSV');
`

**Comment by oklonova** [comment]
Thanks for the answers!

@chunhuaicheng, I will look at the module, thanks. I have all the filters for now, so the only things that I need is export to a file.

@btski, almost exactly. I want  to query the feature table from the organism page (Drupal's node_load function does not work here, because it loads more info about organisms). I was not sure how to access chado tables from within drupal modules. 
chado.tablename works in psql, but not in the template files. 
chado.feature chado_feature was exactly what I need to access that table, thanks again!
(I do not need organisms since I have each feature's ID available, so can query by them instead). 
Sorry for a long question! Just want to make sure I do not miss anything.

**Comment by spficklin** [comment]
@oklonova apologies for not responding. I've been out of town.  Did you get a resolution to the problem?

**Comment by oklonova** [comment]
Hi,
yes, thanks. The answer was "FROM chado.feature chado_feature".
Just a small thing which I am wondering about now: is chado_generate_var() more preferable than SQL when we need to get only some info about features from a chado database? Do you happen to know anything about performance, time or any other things that one should be aware of when using either of these?
