### ISSUE TITLE
New publications layout

### ISSUE THREAD

**Issue by shawnawsu** [tripal/tripal#511]
@laceysanderson has suggested we change the layout of the publication content. Here are her original remarks from ticket #496 : 

> I wonder if we shouldn't discuss a better default though. I think it would be pretty generic to change the settings as follows and it would show a lot more information by default. Currently it's annoying for an admin to drag every single chado property into a pane ;-) (screenshot of settings)
> 
> pull the abstract out of the summary table but within the summary pane
> show all other chado property fields in an "Metadata" pane
> also show the following fields in the "Metadata" pane: publisher, publisher location, page numbers, year, issue, series name, volume, title of the volume.
https://user-images.githubusercontent.com/1719352/42120919-a2300346-7bd8-11e8-87df-26cc6da0a7a8.png

**Comment by spficklin** [comment]
I think we may need some input from other users to get a consensus about what would be best.

**Comment by laceysanderson** [comment]
I'm concerned that no input is forthcoming and I feel the current publication page reflects badly on Tripal. Furthermore, due to the number of fields it is non-trivial to configure. I think my suggestions are very generic and more easily changed due to the grouping of properties/metadata. **Can we go with my suggestion for now @spficklin but be open to change it in the future?**

For easy readability, my suggestion was:

- pull the abstract out of the summary table but within the summary pane
- show all other chado property fields in an "Metadata" pane
- also show the following fields in the "Metadata" pane: publisher, publisher location, page numbers, year, issue, series name, volume, title of the volume.

**Comment by spficklin** [comment]
Just to clarify, you think the default page for publications is bad?  Here's what the demo site shows:

http://demo.tripal.info/3.x/bio_data/667

And it's what I get on my setup as well.

**Comment by laceysanderson** [comment]
yes 😬  I feel that it's nothing like what users/admin expect out of a publication page... but that very minor changes would fix it.

The biggest things are 
- the abstract in the table --you would never see that on a journal website
- 90% of the meta data is excluded from the display (disabled) by default. This hurts my meta-data loving heart and is a pain to remedy since there are so many fields associated with a publication.

I think it's important to remember that most Tripal admin **don't** change the defaults and I think it's particularly likely for the publication content type which is usually not a high priority.

**Comment by spficklin** [comment]
I honestly don't see a problem with the abstract in the table.  I don't find it ugly.   But if you feel strongly about it I'm not opposed to moving it out.  If you think we should include more of the metadata I think a properties tab would be good for all of that other "stuff".

**Comment by laceysanderson** [comment]
Closing as it's just not a priority.
