### ISSUE TITLE
One field shows up as field type "Text" instead of Chado Property

### ISSUE THREAD

**Issue by risharde** [tripal/tripal#517]
Hi @bradfordcondon @shawnawsu @laceysanderson 

I am experiencing a strange problem on a vanilla Tripal install while building my module. I was able to use chado_insert_property to add the default fields with the exception of this field (genus), for some reason, it shows up as a field type "Text" instead of Chado Property and no values get saved when I try to create a new contact via the Add Content link (the default content type form). I'm wondering if chado_insert_property pulls an instance of the field since I see genus is already in the organism type. Any advice on how to avoid this?

> 

			$status = chado_insert_property(
			  $record, 
			  array(
				'type_name' =>'genus',         // the cvterm.name to lookup type_id
				'cv_name' => 'taxonomic_rank',     // the cv.name to lookup type_id
				'value' => 'null1'             // the actual value of the property.
			));

**Comment by shawnawsu** [comment]
Sorry for the delay @risharde. Can you tell us your Chado version, drupal release, what tripal branch you're on, and php version? And is there a github project you can point us to?

**Comment by bradfordcondon** [comment]
You are adding genus as a chado property to contact?   If that's correct, I dont think thats what you intend to be doing, as contact table describes a person, not the data the person submitted.


If the user is submitting, say, an organism, there is already a Genus field attached to organism, using the cvterm you are trying to add as a property: TAXRANK: 0000005.  I don't *think* this would be a problem, but maybe.  It would definitely prevent you from using this CVterm as a property field attached to **organism** because that CVterm is already in use.

**Comment by risharde** [comment]
Yes @bradfordcondon, we intend to do that under what our requirements are currently but maybe just to clarify a bit, the genus fields are in this case telling people that the specific contact has a specialty in this specific genus field if that makes sense. The genus field basically holds the name of the genus/species and nothing more at this point.

TAXRANK: 0000005 <--- unfortunately it seems to be a possible bug since I'm running very lean, basic Tripal 3.0 setup with Chado 1.3 structure. No additional modules other my dev module.

**Comment by bradfordcondon** [comment]
So it sounds like a potential bug where if a chado property field uses "genus" it will get messed up with the organism's genus field, even though we're attached to a contact.  

We saw something similar with publications, but the other way around actually--- a property was interfering with a field (title, maybe?) because they used the same term.

I'm keeping this open as a potential bug to get to some day.

**Comment by spficklin** [comment]
There's not been any further discussion since October, so I'm closing this. Please comment if not.
