### ISSUE TITLE
Slow static pages (i.e. Drupal nodes) caused by adding Tripal Content to the menu

### ISSUE THREAD

**Issue by chunhuaicheng** [tripal/tripal#538]
### System information

* Tripal Version: 7.x-3.x
* Drupal Version: 7.59
* PostgreSQL Version: 9.4
* PHP Version: 7.0.30

### Issue description

This problem will probably affect sites with expandable menu links that show on all pages. The pages are slow to load when you have Tripal Content added to the menu as link items. The more links you add, the slower the performance of the site will be. We have 11 'Organisms' added to the menu for quick access and it drags the performance for our site. 

The slowness is caused by checking permission on each link so Drupal can decide whether to show it in the menu or not. The permission checking process includes loading the entities and it's slow because the organism entities are trying to attach all its fields.

#### Steps to reproduce
1. Go to a page that shows the 'main menu'
2. Add some 'Organisms' to the 'main menu' as quick links, the more items you add the slower the page will load.

#### Error messages and screenshots

```
error message
```

**Comment by almasaeed2010** [comment]
I did a quick profiling and here are my results for a brand new tripal site with 200 mRNA, 1 Organism and 1 Analysis

|Number of items in menu|Time to load the home page|
|-------------------------|---------------------------|
|2|328 ms|
|3|493 ms|
|4|545 ms|
|5|689 ms|
|6|728 ms|
|7|878 ms|

The items in the menu point to `bio_data/#` links. There is an obvious increase in time and it would probably be more if the entities had more fields.

**Comment by almasaeed2010** [comment]
So changing the following lines to not use `$wildcard` and instead pass the entity id fixes the issue. This requires reimplementing `tripal_view_entity()` and `tripal_entity_access()` to handle the id instead of expecting an object. With that, we can load only a single field using `tripal_load_entity()` instead of loading all the fields. Or if there is a better function to pull the bundle name without having to load the entity at all, it'd be preferable.

https://github.com/tripal/tripal/blob/188a9f3eb6b03d5b21e63ec95915153478773e5d/tripal/includes/TripalEntityUIController.inc#L62-L82

**Comment by almasaeed2010** [comment]
PR submitted #542

**Comment by spficklin** [comment]
PR merged.. closing this issue.
