### ISSUE TITLE
Error message: array_key_exists() expects parameter 2 to be array

### ISSUE THREAD

**Issue by risharde** [tripal/tripal#561]
Hi guys, any idea what causes this error message? I keep seeing this at the top of the pages. It doesn't seem to affect functionality per say but would like to get to the bottom of this one. Please let me know, thanks!
> 
Warning: array_key_exists() expects parameter 2 to be array, boolean given in tripal_get_term_details() (line 396 of /var/www/Drupal/sites/all/modules/tripal/tripal/api/tripal.terms.api.inc).

**Comment by spficklin** [comment]
Hi @risharde we'll look into it.  I think you're right though, it's just an annoyance.   Can you give some examples of pages where you see this appear so we can confirm?

**Comment by laceysanderson** [comment]
@risharde are you still experiencing this? Can you provide us with some examples of pages where you see this appear so we can confirm?

**Comment by bradfordcondon** [comment]
i haven't seen this error in a long while. 

Could be the `array_key_exists` call at 358 (different from 396 in the log, but the file has changed  since this issue was posted )

https://github.com/tripal/tripal/blob/13679f3c55c555b33e87ced5c9aab2204bf0cdaf/tripal/api/tripal.terms.api.inc#L339-L361

if im right, its cases where `$term` is null.  We know `$vocabulary` and `$accession` arent null because we check for that first... 

we could add a `!$term` check before `array_key_exists`?  what do y'all think...

**Comment by laceysanderson** [comment]
I like the idea of adding a `!$term` check as it's own "if stanza". That way, we can log an error and return FALSE since if there's no term, we can't find details for it.

```php
if (!$term) {
  tripal_report_error(...);
  return FALSE;
}
```

**Comment by spficklin** [comment]
This looks like it was fixed but never closed.
