### ISSUE TITLE
Pub title field should not  be of 'Chado Property' type

### ISSUE THREAD

**Issue by chunhuaicheng** [tripal/tripal#572]
### System information

* Tripal Version: 7.x-3.x
* Drupal Version: 7.59
* PostgreSQL Version: 9.54
* PHP Version: 7.0

### Issue description

The Pub Title field is stored as a 'Chado Property' which does not use the 'title' column in the 'pub' table. This has caused our site to have empty title for newly imported pubs.

#### Steps to reproduce
List fields for the Publication Content Type e.g. Go to /admin/structure/bio_data/manage/bio_data_5/fields
The 'tpub__title' field has 'Text' field type and 'Chado Property' widget in its setting.

**Comment by spficklin** [comment]
So this problem is caused by the following (after offline discussion with @chunhuaicheng).  If a site has a 'Title' as an entry in the pubprop table of Chado it conflicts with the pub.title field.  Tripal v3 prefers to create a field for the property rather than for the table column.   The reason that @chunhuaicheng was having this problem with the Title is because the Tripal Pub Importer at some time created properties for all data.  The site he is upgrading has some of those pubs that were loaded at a previous time.  The Pub Importer no longer does this.  It doesn't duplicate the title as a property.  So the Title property didn't exist for new records, but did for older ones.   When the site was upgraded to Tv3 and the Publication content type was created it added a "Title" field but linked it to the property rather than to the pub.title column.  So, when Tripal published the new pubs it tried to look for a title using the non-existent 'Title' record from the pubprop table... Therefore all of the titles were blank for the new pubs.

I've submitted a fix.

**Comment by spficklin** [comment]
I've added this as 'URGENT" as @chunhuaicheng is hoping to put a new Tv3 site live ASAP.  

I will submit the PR for the fix if @chunhuaicheng confirms it works.

**Comment by chunhuaicheng** [comment]
Thank you Stephen. I just tried it by removing and recreating the field. It works. The title field is now created as a Text type with TextField widget.

**Comment by spficklin** [comment]
Great Thanks. I'll add the PR.  When I do since you've already tested it can you go in and just comment that you tested it and mark it as approved (like you just did here)?

**Comment by spficklin** [comment]
I went ahead and marked it for you and referred to this issue.

**Comment by chunhuaicheng** [comment]
Before you close this issue. I also found that if you 'Edit' a pub, the title text field isn't populated with the value. Don't know if this is caused by the same bug or not.

**Comment by chunhuaicheng** [comment]
Never mind. It was the old widget still showing on the top of the Edit page. Found the new title field that has the value properly populated.

**Comment by bradfordcondon** [comment]
resolved, thank you @spficklin
