### ISSUE TITLE
Create_point missing function: now in a new context

### ISSUE THREAD

**Issue by oklonova** [tripal/tripal#597]
Hi,

I have seen in earlier issues that this happens with dumps or insertions into featureloc table. I want to delete all features from chado (truncate table chado.feature cascade), but this appears:

SELECT box (create_point(0, $1), create_point($2,500000000))^HINT:  No function matches the given name and argument types. You might need to add explicit type casts.QUERY:  SELECT box (create_point(0, $1), create_point($2,500000000))CONTEXT:  SQL function "boxrange" during inlining

Happened several times with the same command, no data get deleted. What am I overlooking?

Tripal 7-2.1
Chado 1.3

**Comment by bradfordcondon** [comment]
hello:

This always happens when you mess with features without PUBLIC in your search path.  It's because the featureloc table has some functions that reference public.



To resolve the error, do this instead

```sql
set search_path to public, chado;
truncate table chado.feature cascade;
```

For what its worth, if you use the tripal API (chado_delete_record) it will handle this for you.

**Comment by almasaeed2010** [comment]
I think there is a typo in @bradfordcondon response.

He probably meant `chado` instead of `feature` in the first SQL line:

```sql
SET search_path TO public, chado;
```

Thanks!

**Comment by bradfordcondon** [comment]
oops yes chado not feature.  thanks for the correction @almasaeed2010

**Comment by spficklin** [comment]
One further correction.  In Tripal, the **correct_point** function lives in the 'chado' schema and by default Tripal does not include chado in the search_path.. only public.  So, @bradfordcondon is correct in his solution, but it's backwards....

**Comment by almasaeed2010** [comment]
So it should be?
```sql
SET search_path TO chado, public;
```

Interesting I didn't think it mattered.

**Comment by bradfordcondon** [comment]
no, he's not saying the order matters. he is saying my explanation was backwards: its not that `chado` needs stuff in public, it's that `chado` references a Chado function `correct_point`.  So if you run the sql without explicitly including chado in your search path, you get the error.

so to be clear:

```sql
SET search_path TO chado, public;
SET search_path TO public, chado;
```
 these are equivalent

**Comment by almasaeed2010** [comment]
Oh I see, thanks for the clarification!

**Comment by spficklin** [comment]
Since we're on the topic.... Tripal v1 used to set the search_path but we had conflicts with the chado.contact table and the public.contact table when both public and chado were in the search path. Which table you got depended on the order of chado and public in the search path. .  So, with Tripal v2 we had to adjust the code to not require the search_path.  But if you're doing operations in straight SQL outside of Tripal like @oklonova then you would still need to set the search_path

**Comment by oklonova** [comment]
Thank you!
