### ISSUE TITLE
developer guide youtube videos?

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#629]
I'd like to share the developer tutorial videos that our undergrad @jwest60 has been working on (i also have one or two).

What would you all think about a "Tutorial videos" Page in the RTD un the developers guide?  I'm thinking just link, title, 1 sentence description of topic.  Once the page is created all groups are welcome to add any tutorials.

### videos
* [Tripal 3 - Setting Up A Website From Scratch With TripalDock](https://www.youtube.com/watch?v=5SOfQLypvdE)

* [Tripal 3 - TripalDock Commands And Site Structure](https://www.youtube.com/watch?v=g_fmONUgG3s)

* [Creating and running Test Suite Tests](https://www.youtube.com/watch?v=hxuiDzRqs9U)

* [Test driven development live demo](https://www.youtube.com/watch?v=zmYZ_HV3b9s)

* [Loading biomaterials (this might be more appropriate as a user's guide?  but i dont have enough for a dedicated page)](https://www.youtube.com/watch?v=7YkPp2443qA)

**Comment by bradfordcondon** [comment]
One could argue that some of these (TripalDock) should only exist on their respective sites instead so please let me know what you think.

**Comment by laceysanderson** [comment]
I love this idea (since the video itself would not be stored in the repo). I think we should include all videos and maybe categorize them as General, Module-specific or Site-Specific. That way everyone can benefit from them. I think I've seen such a page on Drupal.org with general and site-specific tutorial videos. 

Drupal.org doesn't list module-specific videos but I think our community is small enough that it might be helpful? Although we may not want to worry about ensuring these are up to date? 

Maybe we make a note of the version and date for each video and have a disclaimer at the top:
> The following videos are provided by members of the community. While we don't ensure the videos are up to date, we would appreciate being [contacted through the issue queue](https://github.com/tripal/tripal/issues/new/choose) if you find a broken link. Also, if you have your own video and would like to contribute, we would love to hear from you!

**Comment by spficklin** [comment]
I like the idea as well and agree with @laceysanderson

**Comment by bradfordcondon** [comment]
merged.
