### ISSUE TITLE
Offer an Unpublish AND delete button for tripal content

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#660]
## Feature Request/Discussion

- [x] does this feature attempt to solve an existing problem with Tripal?

### Description

When a user deletes an entity via the GUI, the corresponding chado record is not deleted.

from @chunhuaicheng 

>However, I think it [deleting an entity] should delete the corresponding chado record as well. Here is our use case:
>Our curator uses the web interface to delete unwanted pubs that were imported by the Tripal pub importer. After she deletes the pubs, they still show up in the Tripal Pub Search (/find/publications) results, even after applying you fix.

I'm inclined to agree with him.  here was my response:

>Deleting a tripal entity, intentionally, does not delete the chado record (thats my recollection of this discussion i've had with stephen).

>I think this is not always the desired behavior, for example in the case described. I would go so far as to say that deleting the chado record should be the default behavior. That said, maybe we need to support both? Deleting the record brings up a dialogue that lets you specify you want to also delete the associated chado record ?

### note

Please do not confuse this issue with the bug reported in #652 and its corresponding PR #653

**Comment by chunhuaicheng** [comment]
I second that supporting both is a good idea. I would suggest changing the name of deleting entity to 'Unpublish' record though. Simply because creating the entity is called 'Publish' in T3.

**Comment by laceysanderson** [comment]
I like changing the label of the delete link/button to unpublish but worry this may be more difficult then we think since it's provided by "Drupal Magic".

My Current Vote: Do not delete from chado --too Dangerous ;-p

I'm very open to re-visiting this but feel currently there is not enough information for me vote "Support both". Primarily we should discuss how this would be configured? What would you prefer @chunhuaicheng since you brought this issue to light?

**Comment by chunhuaicheng** [comment]
It's fine for me not to change the current setup. I'll still need a mechanism to delete data though. Any suggestion how to 'really' delete data from chado without having to issue SQL?

**Comment by bradfordcondon** [comment]
>Do not delete from chado --too Dangerous ;-p

I just don't understand this: would you elaborate?  I think of Tripal as a way to serve and administer Chado content via Drupal.  Why leave the D out of CRUD?  Is it really only meant to be a one-way look into Chado?

How about instead of supporting both, we add an admin setting where you can check "Delete both Chado & Drupal records on delete" and "Delete only Drupal records on delete"?  That would be relatively painless wouldnt it?  Tripal checks a global variable before deleting the chado record?

**Comment by laceysanderson** [comment]
> > Do not delete from chado --too Dangerous ;-p

> I just don't understand this: would you elaborate? I think of Tripal as a way to serve and administer Chado content via Drupal. Why leave the D out of CRUD? Is it really only meant to be a one-way look into Chado?

My concerns with delete are two fold:
1. collaborator mistakes could cause data to be deleted that shouldn't be.
2. bugs in Tripal could cause more data to be deleted then intended. 

Concern 1: Could be mitigated by setting of fine-grained permissions to ensure only trusted collaborators can delete their own content and perhaps only admin could delete content regardless of ownership. Luckily this can already be done with the current setup, although we seem to have lost the ability to restrict it to their own content. 

I would want  the delete/unpublish distinction per content type as well. For example, I would want chromosome, contig, gene, variant to be "Unpublish" only even for trusted collaborators, since these are loaded in bulk from published datasets. However, germplasm and genetic markers, should be fully deleted by trusted collaborators (both Drupal & Chado).

Concern 2:
This is the main reason I say dangerous as I have nightmares on programatically-derived Delete queries not being specific enough causing more data or incorrect data to be deleted. This can be mitigated by extensive unit testing (Yay TripalTestSuite!) but still makes me hesitate...

**Comment by bradfordcondon** [comment]
Thanks for the thoughtful response @laceysanderson . I can understand erring on the side of caution for both cases.  When thinking about collaborators, I am not usually thinking about them for admin permissions unfortunately.    But I think we're in agreement that providing more refined permissions perhaps via HQ could help with this. I am often thinking of the case where **a site doesnt have SQL-savvy admins**.  They can never delete content, and old content keeps resurrecting when they publish!  I want to avoid that scenario.

Part 2 is a very serious concern too.  In my experience we're usually deleting from chado directly programmatically though?

**Comment by laceysanderson** [comment]
> I am often thinking of the case where a site doesnt have SQL-savvy admins. They can never delete content, and old content keeps resurrecting when they publish! I want to avoid that scenario.

True! That is a Very good reason to support true deleting from Chado!

> Part 2 is a very serious concern too. In my experience we're usually deleting from chado directly programmatically though?

In order to make the delete query generic we will need to use the Chado Schema API and build the query programatically. This is the part that scares me since if the primary key is left off the query we could delete the entire table 😨 Of course, this can be fixed with good, careful programming and unit testing 🤞 but is still worth concern 🤷‍♀️

**Comment by bradfordcondon** [comment]
after discussion, we like unpublish and delete support.

Need to clarify permissions ie current delete is unpublish, and create new permission for uber deleting.
warning on uber delete.

**Comment by spficklin** [comment]
I agree

**Comment by jhumann** [comment]
Is there any more movement on this?  I am very interested in the options to "Unpublish" and "Delete" mainly because the pub importer occasionally imports a publication we don't want.  And in T2, when I deleted the feature on the website, it also removed it from chado.  Now with T3, I have to make sure I note the pubID number, delete it on the website (which I guess is 'unpublish') and then use a separate step to delete the actual record from chado.  I would love to have this done in one step.

**Comment by spficklin** [comment]
Thanks @jhumann for bringing this back up.  After looking over all of the previous comments here's what I think we need to do

1.  Have permissions that distinguish between "Unpublish" and "Delete" so that the site admin can fine-tune those.
2.  Have both an "Unpublish" and "Delete" button on each entity page.  

For concern #2, there is no fancy delete query for that needs to be executed that could cause side effects.  The entity maintains the chado base record_id.  Since all entities are base records, the only side deletes will be those in a CASCADE DELETE relationship with the base record.

**Comment by laceysanderson** [comment]
This functionality has been officially merged! You can now (in the most recent dev version) delete from chado by clicking the delete button. The original unpublish functionality is still available with an unpublish button in the same spot as the original button (both delete and unpublish are on the right side of the edit form).
