### ISSUE TITLE
Spaces in code

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#693]
We've had several pull requests lately where there are hundreds of line changes simply removing trailing white space.  I know code editors can be setup to automatically remove trailing spaces but apparently not all of us have that feature turned on and it makes reviewing some of these pull requests rather difficult because there are so many lines to check through.  We need a uniform setup in our IDEs.

**Comment by bradfordcondon** [comment]
A) I agree, and of course, see #310 where I make a big stink about having obvious IDE configs.  
B) Fortunately much of this issue is offset by the ability to hide white spaces in PR review: see  image below.

![screen shot 2018-10-01 at 1 40 55 pm](https://user-images.githubusercontent.com/7063154/46305511-a5530500-c57f-11e8-95b5-d78e126bfc77.png)


Still it's noise that i would like to get rid of...

**Comment by laceysanderson** [comment]
I think the easiest way to get rid of this would be to

1. Apply #361 which will hopefully be done after 3.0 is released. This will remove all current whitespace issues.
2. Do Not approve PRs with trailing whitespace :shrugs:

I personally don't think "a uniform setup in our IDE's is likely to be helpful since we all use different ones -heck some of us, myself included, use multiple. 🙃

**Comment by spficklin** [comment]
Okay.  Fair enough.
