### ISSUE TITLE
Error generated during tripal_export_views_integration + Temporary Fix

### ISSUE THREAD

**Issue by risharde** [tripal/tripal#712]
Tripal Version: 7.x-3.0-rc3

Initial Page Error:
```
PDOException: SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: "views-integration" LINE 1: SELECT * FROM tripal_views WHERE setup_id='views-integration... ^: SELECT * FROM {tripal_views} WHERE setup_id=:setup; Array ( [:setup] => views-integration ) in tripal_export_views_integration() (line 726 of /var/www/Drupal/sites/all/modules/tripal/tripal_chado_views/api/tripal_chado_views.api.inc).
The website encountered an unexpected error. Please try again later.
````

URL location: 
admin/tripal/storage/chado/views-integration/export/143

File location: 
sites/all/modules/tripal/tripal_chado_views/api/tripal_chado_views.api.inc

Temporary (nasty) fix:
function tripal_export_views_integration($setup_id)
`$c_path = current_path(); $c_path_parts = explode('/',$c_path); $c_path_parts_len = count($c_path_parts); $setup_id = $c_path_parts[$c_path_parts_len - 1];`
// Main setup details

**Comment by bradfordcondon** [comment]
ok, confirmed at http://tripal.test/admin/tripal/storage/chado/views-integration/export as well.  Thank you for reporting.

**Comment by bradfordcondon** [comment]
`tripal_export_views_integration` is being called with the string `views-integration` in the query 
```
  $r = db_query("SELECT * FROM {tripal_views} WHERE setup_id=:setup", array(':setup' => $setup_id));

```
I get this at 

http://tripal.test/admin/tripal/storage/chado/views-integration/export

and any int for http://tripal.test/admin/tripal/storage/chado/views-integration/export/2, 3, 4, whatever you pass in.

I dont have any background info whatsoever here so i cant make sense of your fix, but ill look into it...


edit: oh duh, the menu item is probably passing in the wrong variable.  lets fix that.

**Comment by bradfordcondon** [comment]
so to fix the problem @risharde has reported I think the answer is to update the `page argument` for the variable from .4 to 6 here:
https://github.com/tripal/tripal/blob/a2f3c1e3414011adfced99e98b15365326904792/tripal_chado_views/tripal_chado_views.module#L117-L125

but what about when no variable is passed:

https://github.com/tripal/tripal/blob/a2f3c1e3414011adfced99e98b15365326904792/tripal_chado_views/tripal_chado_views.module#L108-L116

?????


I THINK that page itself just shouldnt be accessed, since you access the menu at `admin/tripal/storage/chado/views-integration` so im going to remove in my PR hopefully someone in PMC will know if thats OK....

Also now your fix makes sense, since you get the url path and parse the correct ID from there.  much more straight ofrward ot fix the hook `menu()` passing of the variable though.

**Comment by laceysanderson** [comment]
I agree with @bradfordcondon fix and have confirmed it fixes the problem for me. Can you check the most recent dev version @risharde and see if it resolves the problem for you as well?

**Note: You will need to clear the cache after updating in order to see the change.**

/remind me in one week

**Comment by bradfordcondon** [comment]
No response from submitter and PR has been merged.  Please let us know if you have further issues.
