### ISSUE TITLE
Unable to Create Content with Optional Contact Field

### ISSUE THREAD

**Issue by laceysanderson** [tripal/tripal#717]
### System information

* Tripal Version: most recent dev
* Drupal Version: 7.x
* PostgreSQL Version: 9.4
* PHP Version: 5.6.7

### Issue description
When trying to create a project I receive 

>  Could not save the TripalEntity: SQLSTATE[23502]: Not null violation: 7 ERROR: null value in column "contact_id" violates not-null constraint DETAIL: Failing row contains (1, 1, null).
>    Cannot save entity

and the form is reset without creating my project.

#### Steps to reproduce
1. Go to "Add Tripal Content" > "Project"
2. Enter a name only and click Save.

*You can also test this with "DNA Library" by only entering the required information and NOT A CONTACT.*

**Comment by laceysanderson** [comment]
There is a temporary fix of removing the contact field from the tripal content type using manage fields.

**Comment by bradfordcondon** [comment]
is anyone working on this issue?  I can look into it tonight...
edit sorry not getting to it tonight, maybe tomorrow...

**Comment by spficklin** [comment]
I am not

**Comment by laceysanderson** [comment]
Feel free if you end up having time! I haven’t even had the chance to look at it yet

**Comment by bradfordcondon** [comment]
oops- this looks pretty straight forward.  The linker contact field should be attached, not the base table contact field.

The fix- less straight forward, since the project fields arent directly added but inferred somewhere along the way...

**Comment by bradfordcondon** [comment]
heres where the contact field gets added. I'm going to sleep on it.  It looks to me like the **base** contact field gets added if the linker table exists? ie instead of `local__contact_widget`, attach `chado_linker__contact_widget` ???  But that can't be right, otherwise, all tables with a contact linker would be broken?


https://github.com/tripal/tripal/blob/be494de1cb223bcb8c4a4d556410fe702b9622cd/tripal_chado/includes/tripal_chado.fields.inc#L2215-L2257


Yep changing the widget and formatter to `chado_linker__contact_widget` resolves the error.... just a simple mistake then?  since the `local__contact` field is manually added to the tables that use it.  I'll submit a PR but let's think on it before labeling it a simple fix...

also need to provide an updatedb that will remove the faulty field and add the new one, i guess?

**Comment by bradfordcondon** [comment]
Yep changing the widget and formatter to `chado_linker__contact_widget` resolves the error.... just a simple mistake then?  since the `local__contact` field is manually added to the tables that use it.  I'll submit a PR but let's think on it before labeling it a simple fix...

**Comment by bradfordcondon** [comment]
resolved with #764
