### ISSUE TITLE
Filtered HTML

### ISSUE THREAD

**Issue by kyrenya** [tripal/tripal#721]
Hi
Using UBUNTU 18.04 and last Tripal v3.0 Release installation
I'm trying to follow the tutorial of the citrus example: 

When creating the analysis, using Filtered HTML doesnt work, I don't get the description text formatted
![image](https://user-images.githubusercontent.com/43243429/47213172-2ab52280-d392-11e8-8d5c-1375fa66b5d5.png). In the text guidelines, by the way, it's written  'Description (Set to Full HTML)' , shouldn't be Set to Filtered HTML?

Thanks!

**Comment by bradfordcondon** [comment]
hello:
both full and filtered html text settings work for me.

<img width="872" alt="screen shot 2018-10-19 at 9 18 06 am" src="https://user-images.githubusercontent.com/7063154/47220509-fb95b580-d37f-11e8-89d0-4a1c259a8a89.png">

maybe another @tripal/core-committers-group member has a better suggestion, but my guesses would be the problem is field setting or theme related. Have you configured the analysis description field at all?  Can you try switching to the default theme and see if the problem persists?


edit: as for which is appropriate, i think the answer depends on who has permission.  If its just the site admin then full is fine.  If you are allowing users to create content then filtered is better.

**Comment by kyrenya** [comment]
I tried with that theme, and: 
![image](https://user-images.githubusercontent.com/43243429/47221623-ce133100-d3ac-11e8-8bb0-6476491c1e75.png)
the edit screen is a bit confusing and mixed: and it didnt result: 
![image](https://user-images.githubusercontent.com/43243429/47221652-e4b98800-d3ac-11e8-9910-590db22a050d.png)

I also trying with the Reload menu.. not lucky. Same unformatted text.
I also highlight than when I choose Filtered HTML, save, look at it, and go back to Edit, the option is still in Full HTML (like not remembering I chose FIltered), dont know if that is normal also.

**Comment by laceysanderson** [comment]
Hi @kyrenya, your edit form does not look right at all. Have you by chance tried configuring or enabled a WYSIWYG module? If so, I would think that's where the problem lies. Try un-enabling any addition extension modules beyond Tripal, Drupal Core and Views and see if that fixes the form.

For context, my analysis edit/create form looks like this:
<img width="1471" alt="screen shot 2018-10-19 at 11 44 05 am" src="https://user-images.githubusercontent.com/1566301/47234833-56390c80-d394-11e8-84db-3765c428a945.png">

**Comment by kyrenya** [comment]
thanks, you were right! 
I enabled this module: 
![image](https://user-images.githubusercontent.com/43243429/47287665-eb354300-d5ea-11e8-84a2-63c657916936.png)
when disabled, the editor worked right! 
thanks!

**Comment by laceysanderson** [comment]
Great! Glad it worked :-)
