### ISSUE TITLE
CrossReference

### ISSUE THREAD

**Issue by kyrenya** [tripal/tripal#722]
Hi
Using UBUNTU 18.04 and last Tripal v3.0 Release installation
I'm trying to follow the tutorial of the citrus example: 

When creating the organism, my link to CrossReference never works.. 

![image](https://user-images.githubusercontent.com/43243429/47213363-aadb8800-d392-11e8-94ba-a5d2a3e42fd8.png)

should link to: 
purl.obolibrary.org/obo/ncbitaxon#NCBITaxon:2711
never loads. 
is that an issue of the OBO or my tripal crossreference config? 

Thanks!

**Comment by bradfordcondon** [comment]
is `purl.obolibrary.org/obo/ncbitaxon#NCBITaxon:2711` the built URL or the desired URL?

If its teh desired URL and the built URL is wrong, what is the built URL?

you can check the configuration of your database crossref by going to `admin/tripal/loaders/chado_db/ ` can you share the relevant DB information?

**Comment by kyrenya** [comment]
This is the address that tries to achive when click in the CrossRef..  so.. then I guess is the built URL isnt it?
I can't find anything related to NCBITaxon in admin/tripal/loaders/chado_db/. 
I just followed the steps in here https://tripal.info/tutorials/v3.x/example-genomic-site/organism for import taxonomy for existing species (Chado NCBI Taxonomy Loader).

**Comment by bradfordcondon** [comment]
Please follow the tripal 3 guide at https://tripal.readthedocs.io/en/latest/user_guide/example_genomics/organisms.html?highlight=organisms.  It's more up to date.  @spficklin is there a reason we still have the tripal 3 user guide up on tripal.info?
OK thanks, in the future if you link what part of the guide you're following that will be helpful for me to answer your questions.

In this case, the bug is that the NCBI taxon db entry is wrong. here's mine: (found by going to the page i linked and searchign for NCBI.)

<img width="1335" alt="screen shot 2018-10-19 at 10 18 42 am" src="https://user-images.githubusercontent.com/7063154/47223989-7a8eec00-d388-11e8-9a6d-291aa2a19bc8.png">


you can see the linkout tripal will build for a given accession is http://purl.obolibrary.org/obo/ncbitaxon#{accession}. This isnt correct.  it should instead be, perhaps, https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?&id={accession}

Thanks for the info, ill mark this as a minor bug.  If you'd like to fix it on your site, change the URL linkout prefix NCBI taxon db entry as i describe above.


PS if you cant find the db entry via search, thats often a symptom that you didnt apply the views patch described in the install process.  please see: https://tripal.readthedocs.io/en/latest/user_guide/install_tripal/manual_install/install_tripal.html?highlight=patch#apply-patches

**Comment by bradfordcondon** [comment]
@kyrenya please see this page of the guide to understand the cross ref field/database linking and whats going on:

https://tripal.readthedocs.io/en/latest/user_guide/example_genomics/cross_refs.html


I've created an issue for the linkout being built wrong by default #724 

Thanks for pointing it out!

any further questions before i close the issue?

**Comment by kyrenya** [comment]
Solved! Thanks a lot! 
I thought I had applied the patches, but apparently sth went wrong. Now I can see the databases in the search. Also changed the URL and now links OK. Thanks again! You can close the issue!
