### ISSUE TITLE
Issue with entity search

### ISSUE THREAD

**Issue by mboudet** [tripal/tripal#734]
### System information

Tripal: 7.x-3.0
Drupal : 7.59 
Postgres: 9.5.8 
Php: 7.1.23

### Issue description
When using one of the entity search form (organism in this case), if a query with no results is selected, a warning pops up.

#### Steps to reproduce
Search for query with no results.

#### Error messages and screenshots
```
Notice: Undefined index: TripalEntity in TripalFieldQuery->execute() (line 127 of /var/www/html/sites/all/modules/tripal/tripal/includes/TripalFieldQuery.inc).
```
When we do a query, we generate two queries : one normal, and one with the 'count' option 
[here](https://github.com/tripal/tripal/blob/5bcbff466be1d6a530df7246cdf3c17ed6b5188d/tripal/tripal_views_query.inc#L264)
(I'm not exactly sure why.. since in this case the queries are exactly the same. Maybe there are some cases where the count query is faster?)
In any case, when the execute() method is called on the count query, we use this code : 

```
if (is_numeric($results)) {
  return $results;
}
return count($results['TripalEntity']);
```
I suppose that in some cases (non entity search maybe?), the query directly return the value. In entities, it returns all the results in $results['TripalEntity'].
However, if there are no results, $results = {}, so $results['TripalEntity'] crashes.
Testing for an empty array should be enough (returning 0 if that's the case)

The normal query (executed after this one) works fine.

**Comment by bradfordcondon** [comment]
>(I'm not exactly sure why.. since in this case the queries are exactly the same. Maybe there are some cases where the count query is faster?)

Hmmm... so what I typically do is have the count query fetch ALL and the regular query fetch whats in the pagination.  This is indeed a much faster way to run the query than fetching all results and then counting them (since you only fetch the fields for whats in your pager).


>Testing for an empty array should be enough (returning 0 if that's the case)

Sure.  Or count being 0, i would think.  Which is what we attempt to do:

https://github.com/tripal/tripal/blob/5bcbff466be1d6a530df7246cdf3c17ed6b5188d/tripal/includes/TripalFieldQuery.inc#L123-L129

maybe count of 0 isnt false, and we should check if count == (int) 0 instead.

### the search tool


https://tripal.readthedocs.io/en/latest/user_guide/searching/default_pages.html?highlight=search#tripal-content-specific-search-tools

Can we add to the docs where to find this search tool?  We use elasticsearch on our site and i can never remember where the default searches are. @mboudet would you be so kind as to remind me where they are so i can test and patch?

**Comment by mboudet** [comment]
> Sure. Or count being 0, i would think. Which is what we attempt to do:

Do you mean in  `$this->count` ? I think the variable is set to True no matter what, since we called `count()` on the query. [According to the docs](https://api.drupal.org/api/drupal/includes%21entity.inc/function/EntityFieldQuery%3A%3Acount/7.x), this variable is just set to indicate it's a count query. (Unless it's modified later?)

> Can we add to the docs where to find this search tool? We use elasticsearch on our site and i can never remember where the default searches are. @mboudet would you be so kind as to remind me where they are so i can test and patch?

As far as I know, they are located in /data_search/*entity_name* (mrna, organism, analysis, etc..).
One view is created for every new entity type.

**Comment by bradfordcondon** [comment]
oh its checking the query type not the count 😆 nevermind.  we can do what you propose, check if the key exists/check if there are results before looking for the key.... are you interested in making the PR yourself?

**Comment by mboudet** [comment]
Sure, I'll add it soon.

**Comment by bradfordcondon** [comment]
thanks for the PR! I'm leaving the issue open because i want to add some documentation for where the search is located since this is the second time its come up and i couldnt find it.

**Comment by bradfordcondon** [comment]
ok never again will i have to ask for help finding the default search views!  Thanks for reporting the issue and submitting the fix @mboudet
