### ISSUE TITLE
Project vs Analyses for Whole Genome

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#804]
Should we update the documentation to use a project for the whole genome example rather than use an analysis?

https://tripal.readthedocs.io/en/latest/user_guide/example_genomics/analyses.html

**Comment by bradfordcondon** [comment]
* projects offer very little- just a few columns.  i dont think we have many functional linker fields, either.

So the example will just have a name and a description, and whatever linkers work out of the box.

* I'm against the adoption of projects for NCBI databases other than BioProject.  I think its confusing, I think it is forcing data into Chado for the sake of Chado.  I think Anayses should be expanded to better represent more complicated analyses or some other solution--- i think adopting project here means we'll adopt it for all other NCBI databases, and each of those project will in turn mean multiple projects.

Thats all to be discussed in Chado obviously, see https://github.com/GMOD/Chado/issues/76

**Comment by laceysanderson** [comment]
I think projects offer an intuitive grouping mechanism for analysis'. **However, I think we should hold off on switching the documentation until we have a field allowing a user to intuitively link/create multiple analysis' for a project.** I feel this way since we don't want to lose metadata they would associate with an analysis.

> projects offer very little- just a few columns. i dont think we have many functional linker fields, either.

Currently projects offer:
- name
- description
- cross reference
- publication
- contact
- relationship
- properties

We are missing:
- project => analysis
- project => feature
- project => stock

**Comment by bradfordcondon** [comment]
I'd really like to discuss and consider the analysis->project mapping more.  Perhaps its something that will have to wait for PAG.

Please consider loading a genome for Bos taurus: lets pick one of the 3 available assemblies: https://www.ncbi.nlm.nih.gov/assembly/GCF_002263795.1

this is assembly is already part of at leaset 2 projects:
[Project](https://www.ncbi.nlm.nih.gov/bioproject/416842)
[Project](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA391427/)
What if we want to add the genome and WGS record as well? By this logic these shoudl also both be projects
[Genome](https://www.ncbi.nlm.nih.gov/genome/82)
[WGS nucleotide record](https://www.ncbi.nlm.nih.gov/nuccore/1358650357)

So we now have 5 projects for this assembly.  A type column will help us, and we can use relationship to link... but IMO, this makes things so confusing for no benefit other than "Chado says so".  Especially because in each case, we likely arent going to have enough information to break teh analysis into multiple sub-analyses from genbank.

Plus we've got at least 2 other assemblies fro this organism which someone might want to load
 [Assembly 2](https://www.ncbi.nlm.nih.gov/assembly/GCF_000003055.6)
[Assembly 3](https://www.ncbi.nlm.nih.gov/assembly/GCF_000003205.7)


Maybe I'm overreacting, but this seems confusing.  Where does metadata go, attached to the analysis?  the project? the parent project?  When we no longer have entities in genbank corresponding 1:1 to records in Chado, we have to make hard decisions.  Plus, the confusion of having a ncbi bioproject db that only corresponds to chado projects in the sense that all NCBI records will).

  I much prefer the idea of creating a new content type specifically for pipeline runs (that isnt part of MAGE), or, opening the analysis c oncept up to include multiple program runs that may or may not be explicitly defined.

**Comment by spficklin** [comment]
So @bradfordcondon and I had a conversation yesterday where I proposed that really we are trying to use the Project/Analysis tables for more than what they were designed for.  We are trying to capture information from two types of workflows

1.  Project Design Flow:  this captures information about a project, whose working in it, what components are part of it, etc.  An example may be a consortium project that funds a whole genome annotation and assembly project.  There are high-level components of a project such as genome assemblies, genome annotations, and various version of those.   Often there may be many tools attempted or explored before finalizing on a final version.  There are lab protocols for data collection, etc.  This goes beyond just a list of analytical tools and input data that an analytical workflow would describe.
2.  Analytical Pipelines:  this captures analytical workflows such as what Galaxy performs or even the manual step-by-step work that an informaticists may do as they use tools and data and string them together. 

We initially thought that perhaps the project and analysis tables are not sufficient to represent the graphs of these two trees.  We could use project, analysis, project_relationship and analysis_relationship tables to model the tree, but I wonder if that's like trying to shove a square peg in a round hole and that another table structure may be better suited to store the graphs.  Could you imagine the user navigating the Tripal UI interface to enter this tree?  Manually specifying the relationships on each entity to build these workflow graphs? Then the developer querying the graph through these tables to display the tree.  I think it would get overwhelming pretty quick.

.... just some additional thoughts.

**Comment by laceysanderson** [comment]
Perhaps this would be a good PAG Hackathon topic. Almost all Tripal sites have genomes to model. If we could decide as a community how best to store this metadata and implement fields to make it intuitive and useful it would be of great use to the community.

**Comment by mpoelchau** [comment]
@laceysanderson great idea! We had to think about this a fair amount for the tripal eutils module (which @Ferrisx4 will be giving a talk about during the Tripal session at PAG). I'd be happy to contribute to or lead a discussion on this during the PAG hackathon.  I suspect that this is not quite ready for anyone to start coding by PAG.

**Comment by mestato** [comment]
PAG codefest update - We tackled the question of analytical workflows/pipelines today and decided the analysis_relationship table could be used to associate the "master" analysis (such as genome assembly) with the individual analysis steps (such as skewer, AllPaths, Canu). Would be nice to expand the description of the analysis table in chado as it currently does not support this approach and to develop a use case or two to show how the data would be inserted. 

We did not discuss project design flow and associating scientists to various parts of a project, but it is worth noting there is project_relationship table and a project_contact table, so we appear to have all the components of chado needed to do that as well. Just need someone to delve into development of a use case/best practice.
