### ISSUE TITLE
Questions about GFF loading and alignment sequence

### ISSUE THREAD

**Issue by songtaogui** [tripal/tripal#822]
Hi,
I have some custom descriptions for genes recorded in the GFF files as "description=XXXXXX" or "product=XXXXXXX", is it possible to show these information in the result-table of "search gene" or "search sequence" tools ?
Besides, the `mRNA` sequences from the alignment failed to wrapped (concatenated by " " rather than "\n" every 50 characters), while  manually uploaded sequences and `CDS` sequences from alignment were correctly wrapped, how to fix that? 

Thank you

**Comment by bradfordcondon** [comment]
hello, sorry about the slow response.

>have some custom descriptions for genes recorded in the GFF files 

I believe that the GFF loader will load all unexpected attributes in the Chado featureprop table, using the `feature_property` namespace: these will consequently be available on the feature entity page using hte Chado property field.   Because they are available as properties, yes, they will be searchable although you might have to set up a custom search page... see https://tripal.readthedocs.io/en/latest/user_guide/searching/default_pages.html?highlight=search


edit: If youre curious what attributes Tripal looks for when loading the GFF (meaning, what attributes will Tripal place somewhere other than featureprop), they are here:  https://github.com/tripal/tripal/blob/a2f3c1e3414011adfced99e98b15365326904792/tripal_chado/includes/TripalImporter/GFF3Importer.inc#L691-L699


>Besides, the mRNA sequences from the alignment failed to wrapped 

Were these in the GFF file or a FASTA file?  Can you please provide an example input file and clarify which importer you were using?

**Comment by songtaogui** [comment]
Thank you for your kind reply.

>Besides, the mRNA sequences from the alignment failed to wrapped

For example, at the [cottongen.org](https://www.cottongen.org) demo-site, while visit the `sequence` tag of the detail page for a transcript, such as [Cotton_D_gene_10013074-BGI-CGP_v1.0](https://www.cottongen.org/node/535317#1566635-413)

The `mRNA sequence` ( from manually uploaded mRNA.fa, I guess ) works fine:
![image](https://user-images.githubusercontent.com/14274330/51363551-85862380-1b13-11e9-982c-c74576236030.png)

But the `mRNA from alignment at Chr8:5567301..5569878-` failed to wrap the sequences by `\n`:
![image](https://user-images.githubusercontent.com/14274330/51363859-dea28700-1b14-11e9-807f-5fe64060dddb.png)

**Comment by bradfordcondon** [comment]
the first sequence is associated with the mRNA feature (the feature.residues column value).  The second, with the spaces, is derived from the sequence of the parent feature (chr8).   

So If I understand you, you'd like the `"  "` whitespace characters to be newlines in the presentation of the CDS, is that right?
Honestly its kind of strange to see the spaces there at all...

**Comment by bradfordcondon** [comment]
Just revisiting this.... those feature pages are with the legacy feature templates, here:
https://github.com/tripal/tripal/blob/7f35a59c5e48bd173d06da51e28d8abbfebc8594/legacy/tripal_feature/theme/tripal_feature.theme.inc#L286

So once this site switches to full tripal 3 entities, this should be a non-issue.  I'd have to have the GFF to confirm that it looks as we'd hope.

**Comment by spficklin** [comment]
There has been on additional comments on this in a few months so I'm closing out the issue.  @songtaogui please comment if you are still having issues and we can try to help further.
