### ISSUE TITLE
About deletion of features and organism

### ISSUE THREAD

**Issue by EugeneKim76** [tripal/tripal#853]
Dear all
I'm using Tripal 2.x.
I deleted an organism(deleted at /#overlay=admin/content) and its features (deleted at /#overlay=admin/tripal/chado/tripal_feature/delete).
After deletion I upgraded Materialized Views.

However, I found deleted data are still exist in chado tables by using postgres command lines below.
 SELECT * FROM chado.organism WHERE organism_id = 55
 SELECT * FROM chado.feature WHERE organism_id = 55

And the deleted organism was also found in chado data loader module.

How can I delete wrong organisms or features?
best,

**Comment by btski** [comment]
You seem to have deleted content pages corresponding to organisms in your database. To delete the database entries themselves, I believe there are two options:

1.) You can revert a bulk load job entirely. This would require tracking the entries inserted into your Chado tables (an option provided in the bulk loader job submission form). I've encountered memory issues using this feature, which doesn't seem to handle complex (large number of tables) and large (many rows) jobs very well.
2.) You can delete the entries manually (using DELETE instead of SELECT in psql). This is the method I personally use. You shouldn't have any problems with this as long as you don't have any Drupal content pages linked to your tables.

If there are other/better options, I'm also interested in hearing them. Thanks.

**Comment by laceysanderson** [comment]
Thanks @btski, I think that summarizes the current options well. My only comment would be for (2) if you do have content then you'll want to clean up orphan pages after by going to Admin > Content > Tripal Content > Unpublish Orphan Content. 

Additionally, there has been more discussion for developing a better way to delete content from chado in #660.

**Comment by EugeneKim76** [comment]
Thanks a lot.

I tried to delete by using commend lines below.
DELETE FROM chado.organism WHERE organism_id = 55;
DELETE FROM chado.feature WHERE organism_id = 55;

However, same error occurred as shown below.
Could you please tell me what must be causing the error to occur when I try to delete data?
best,

ERROR:  function create_point(integer, bigint) does not exist
LINE 1: SELECT box (create_point(0, $1), create_point($2,500000000))
                    ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
QUERY:  SELECT box (create_point(0, $1), create_point($2,500000000))
CONTEXT:  SQL function "boxrange" during inlining
SQL statement "DELETE FROM ONLY "chado"."featureloc" WHERE $1 OPERATOR(pg_catalog.=) "feature_id""

**Comment by btski** [comment]
You might find [this](http://tripal.info/documentation/migrate_chado) helpful. From the source:

```
SET search_path = frange,chado,pg_catalog;
CREATE INDEX bingroup_boxrange ON featuregroup USING gist (chado.boxrange(fmin, fmax)) WHERE (is_root = 1);
```

It is necessary to run these SQL commands because of an error that can be found in the db_restore.log file.  The error appears as follows: psql:tripal.sql:1932580: ERROR:  function create_point(integer, integer) does not exist LINE 1: SELECT box (create_point(0, $1), create_point($2,500000000)) HINT:  No function matches the given name and argument types. You might need to add explicit type casts. QUERY:  SELECT box (create_point(0, $1), create_point($2,500000000)) CONTEXT:  SQL function "boxrange" during inlining This error occurs when trying to create indexes for the frange.featuregroup table.  

There are nested PSQL function calls needed to build one of the indexes for this table and the pg_dump utility does not set the necessary search_path.  Because this error is a problem with creation of an index there will be no data loss from the import.  But, the an index on the frange.featuregroup table will be missing.  The commands above restore that index.

**Comment by EugeneKim76** [comment]
Thanks @btski!
I used command lines you suggested before deletion.
In my case,

drupal=# SET search_path = frange,chado,pg_catalog;
SET
drupal=# CREATE INDEX bingroup_boxrange ON featuregroup USING gist (chado.boxrange(fmin, fmax)) WHERE (is_root = 1);
ERROR:  relation "bingroup_boxrange" already exists

Anyway, after running SQL commands, deletion were done successfully.
Thanks a  lot.
Best,
