### ISSUE TITLE
How to use h5ai for FTP downloading in tripal 

### ISSUE THREAD

**Issue by songtaogui** [tripal/tripal#859]
Hi,

I have noticed the demo site [treegenesdb](https://treegenesdb.org/) uses [h5ai](https://larsjung.de/h5ai/) as FTP server interface, and I would like to use h5ai too, is there a tutorial on how to set h5ai for tripal FTP server?

Thank you,

Best wishes,

Songtao Gui

**Comment by bradfordcondon** [comment]
would someone from treegenes be able to respond?

 @tripal/wegrzynlab

**Comment by Ferrisx4** [comment]
Hello @songtaogui and thanks @bradfordcondon for highlighting.

It should be noted that h5ai is not a true FTP (as in the protocol) server, but merely a pretty HTML indexer for public files. Additionally, there is no direct integration between Tripal and h5ai currently. 

In the case of TreeGenes, we have a collection of files that we have made available in a directory on our webserver. This directory is served with h5ai as the indexer (instead of using Apache or NGINX's default indexer or Directory Lister functionality). 

At TreeGenes, on the Tripal side, we just link to these files from within our various pages (organism, species, etc). Our files are organized in such a way that we were able to programmatically generate those links.

For TreeGenes, other than upgrading our PHP version, the normal h5ai installation instructions were sufficient to get it working for us.

**Comment by a2htray** [comment]
@Ferrisx4 We did as you say, but how to resolve the problem of URL path for drupal? the following is the configuration:

```conf
ServerAdmin webmaster@localhost
DocumentRoot /var/www
Alias /h5ai /var/www/_h5ai
Alias /drupal /var/www/html
DirectoryIndex index.html index.php html/index.php public/index.php
```

The error of `404 Page Not Found` occurrences when we access these URL without prefix `/drupal`

**Comment by songtaogui** [comment]
Hi, @Ferrisx4, @bradfordcondon

**Comment by songtaogui** [comment]
Hi,
@bradfordcondon @Ferrisx4 

Thank you for your kindly help.
We have finally get the h5ai working. 

Thank you 👍 

Best wishes,
Songtao Gui
