### ISSUE TITLE
Migrated organism missing its image

### ISSUE THREAD

**Issue by laceysanderson** [tripal/tripal#86]
Process: Upgrade from 2.1 => 3.0-beta3: content migration for a generic Tripal 2.1

Steps:
 - Choose to Migrate content (step2: admin/tripal/storage/chado/migrate) for Tripal v2 Organisms
 - Check the organism page after running the Tripal job... there is no image.
I would guess this is because the Tripal v2 organism image is not stored in Chado. Anyway, not critical but thought I would mention it since it is core Tripal and we tell them to add an image in the tutorial.

**Comment by spficklin** [comment]
There should be an image there. We specifically tried to address this issue.  I guess it broke. Assigning to Chun-huai.

**Comment by spficklin** [comment]
Do you have the most recent development branch?

**Comment by laceysanderson** [comment]
I did when I posted this issue. Would you like me to re-check?

**Comment by spficklin** [comment]
No worries.  just checking.  I believe @chunhuaicheng  is looking into it so we'll be back in touch!

**Comment by chunhuaicheng** [comment]
Hi Lacey,
Could you pull the latest code and check if the problem is resolved please? The organism image migration was fixed after 3.0-beta3 was released. It checks if an organism image is uploaded as a Drupal managed file first. If it's not, the code will try to migrate the organism images found in the 'sites/default/files/tripal/tripal_organism/images' folder using the [Genus]_[species].jpg or [nid].jpg as the image file name.

**Comment by laceysanderson** [comment]
Confirmed that this is working now, although the image didn't appear at first. I had to re-order the fields on "Manage Display" and then it appeared?
