### ISSUE TITLE
When migrating 1 node type => multiple entity types, only migrates the first.

### ISSUE THREAD

**Issue by laceysanderson** [tripal/tripal#87]
Process: Upgrade from 2.1 => 3.0-beta3: content migration for a generic Tripal 2.1

Steps:
- Choose to Migrate content (step2: admin/tripal/storage/chado/migrate) for Tripal v2 Features
- Select "Gene", "Supercontig", and "mRNA" from the Tripal v3 content type checkbox list and click "Migrate Feature"
- Run Tripal job
- Check "Find Tripal Content" and see only Genes have been sync'd :-(

Repeating the above steps but only clicking one Tripal v3 type does allow me to sync the other two separately without additional error...

**Comment by spficklin** [comment]
Are you using the most recent development version or beta3 version?

**Comment by spficklin** [comment]
Also, just curious... you have supercontig pages?

**Comment by laceysanderson** [comment]
I was just upgrading content from the Tripal 2 tutorial to Tripal 3 before launching into a full KnowPulse upgrade :-) KnowPulse doesn't have supercontig pages, although it does have chromosome and contig pages :-)

**Comment by chunhuaicheng** [comment]
Hi,
I can not reproduce this problem. I checked three feature types (i.e. 'bin', 'chromosome_arm', and 'QTL') and they're all migrated in the first run. Could you try if it's fixed in the latest development branch please? 

If the problem still exists, could you add a 'print_r($migration)' inside the 'tripal_chado_migrate_records($migration, $job_id = NULL)' function (i.e. line 574) to this file: 'tripal/tripal_chado/includes/tripal_chado.migrate.inc' and let me know what it prints when launching the tripal_job please?

**Comment by laceysanderson** [comment]
Confirmed that either this is fixed in the most recent dev or no longer repeatable. Marking as fixed 👍
