### ISSUE TITLE
Legacy templates and migration confusion

### ISSUE THREAD

**Issue by mdondrup** [tripal/tripal#890]
Hi,
I am trying the migration from 2.1 -> 3.1

So far, the update worked nicely as documented. But I find the inline documentation on the migration part confusing. In particular, I wish to switch on and off legacy templates and new templates to compare their functionality. Under Migration step 3, it appears as if legacy templates can be switched on and off without additional steps required, however, if I switch off legacy templates, they still appear as legacy for some types. Does one have to flush cache, or run migrate step 2 again, or is there another problem with the migration I haven't noticed.

Other things that are a bit unclear to me:

- legacy templates and new templates seem to have different URLs after migration, but there is no mention or an example for these new and old paths.

"This allows you to keep existing pages while reviewing and customizing the Tripal v3 content types." It should be described how one can access both at the same time.

 This should be documented under migration step 2 giving an example of old and new URLs.

- What happens if step 2 is run repeatedly for the same type. 

- step 4: `WARNING: Any of the following options cannot be undone.`
Does that mean none of the following actions can be undone? Also it is not really clear to me why un-publishing cannot be  reverted.

**Comment by bradfordcondon** [comment]
Pinging @chunhuaicheng as I think he's the primary author of the migration.  In particular i dont know anything about the legacy templates...

>It should be described how one can access both at the same time.

i dont understand the question/problem... you would compare the entity page to the node page. 

Re step 4 at least- you cant re-publish to nodes because now they will publish to tripal 3 entities.  You'd have to downgrade back to T2 and that would cause so many problems i wouldn't entertain it :P . Consider step 4 all as **irreversible actions**.

**Comment by chunhuaicheng** [comment]
Here's some clarification about the Tripal v3 content types (i.e. Drupal Entity) and Tripal v2 content types (i.e. Drupal Node):

The Tripal v3 content types have a URL of '/biodata/[eid]' and you can choose to apply the 'legacy templates' for them so they'll look the same as the old v2 content. If you 'switch off' the legacy templates, the v3 content will have the default look which you can configure using Drupal's Entity/Field API (i.e. by going to '/admin/structure/bio_data')

On the other hands, The Tripal v2 content types have a URL of '/node/[nid]' and it always uses the 'Legacy template'. (You can't switch it off)

Usually after migration, you'll end up with two copies of linker data (i.e. node and entity). Therefore, Step 4 allows you to remove the nodes if you only want one copy (of entities). Removing the nodes cannot be undone because there is no 'sync data' function to re-create nodes in T3 anymore. The equivalent function in T3 is 'publish data' that creates entities. Not just removing node, all other functions in Step 4 are irreversible.

**Comment by laceysanderson** [comment]
@mdondrup is the process more clear to you now?

The current [step 2 documentation on tripal RTD](https://tripal.readthedocs.io/en/latest/user_guide/install_tripal/upgrade_from_tripal2.html#step-3-use-legacy-templates-optional) states

> This allows you to keep existing pages while reviewing and customizing the Tripal v3 content types. Site visitors can continue to visit the Tripal v2 pages. Tripal v3 content types may remain private while customization is underway. Once customization is completed a subsequent step will allow you to swap out Tripal v2 pages for the newer Tripal v3 pages. 

But [step 3 on RTD](https://tripal.readthedocs.io/en/latest/user_guide/install_tripal/upgrade_from_tripal2.html#step-3-use-legacy-templates-optional) doesn't actually explain what @chunhuaicheng does above. Would it be helpful to add that there?

**Comment by spficklin** [comment]
Since there's been no further comments since March I'm closing this out.  Please comment if you think it should be reopened.
