### ISSUE TITLE
Create Additional Widget Type Option

### ISSUE THREAD

**Issue by reynoldtan** [tripal/tripal#899]
Hello! I would like to create an additional widget type option (as shown by the mockup below) for the `data_identifier` field which currently only supports "text field". The widget type should be able to:

>This should be a generic field widget that will work for any chado table (e.g. feature or stock). It will automatically fill in the uniquename based on the primary key and a configured prefix. On create, it will show "Will be set automatically on creation" and on edit, it will show a textfield with the value that is disabled.

https://github.com/tripal/trpfancy_fields/issues/11

![add-widget](https://user-images.githubusercontent.com/15472253/54717346-9821d680-4b1d-11e9-8ebe-8c1b0ab2637d.png)

I tried creating a field with just a widget but it is not showing the widget option.

**Comment by laceysanderson** [comment]
I'm not sure how to do this since `data__identifier` uses the Drupal text field rather then a Tripal field. Simply setting the widget [`$field_types`](https://github.com/tripal/tripal/blob/7.x-3.x/tripal_chado/includes/TripalFields/data__accession/data__accession_widget.inc#L9) to `data__identifier` doesn't seem to work. Is there another step @spficklin?

**Comment by spficklin** [comment]
Okay, so it's been awhile since I worked on this.  But, I believe you should be able to create a new widget class.  Place it in this location:

`sites/all/libraries/TripalFields/{field_name}/{field_name}_widget.inc.`

Even though you are creating just a widget for an existing field, you have to give it a name as if it were a full field.  Then create the {field_name}_widget.inc file that defines your widget.  

In your widget Class definition, be sure that you specify the 'data__identifier' field as a field type that the widget is compatible with:

```php
  // The list of field types for which this formatter is appropriate.
  public static $field_types = ['data__identifier'];
```
You should then be able to go into the `Admin` > `Tripal Content Types`, select the content type then manage fields and click the `data__identifier` field. You can then click the `widget type` tab to switch the widget type to your new widget.

It's clear we need to add this information to the online documentation.  I'm going to mark this issue as a documentation issue to remind us to add that in.

**Comment by spficklin** [comment]
Alternatively, if you want this in a module, you can put the new widget class in you module in a similar path:

`sites/all/modules/{your_module}/includes/TripalFields/{field_name}/{field_name}_widget.inc.`

**Comment by laceysanderson** [comment]
Ok, after much digging I figured out why this wasn't working! As suspected it was because data__identifier is actually a drupal text field.

# Corrected Instructions
In your widget Class definition, you need to enter which field **Types** this widget it compatible with. In the case of Tripal/Chado fields, this will be the machine name of the field (e.g. `obi__organism`). However, some fields on Tripal Content Types actually use Drupal Fields (e.g. data__identifier is actually a Drupal Text field). In this case, the $field_types array should include the Drupal field type (e.g. `text`) rather then the field machine name.

```
// The list of field types for which this formatter is appropriate.
public static $field_types = ['text'];
```

**Comment by spficklin** [comment]
Looks like this was resolved!
