### ISSUE TITLE
Is it possible to insert a tripalentity form into user registration form?

### ISSUE THREAD

**Issue by risharde** [tripal/tripal#907]
Hi guys, I know this is a strange question but hopefully not an abomination to perhaps Drupal standards but I have a unique issue in which I have a Tripal Content Type submission form that I'd like to be a part of the user registration process and thus the question in the title.

Can you guys let me know if that should be possible? 
Just to clarify, I want to insert the Tripal content type submission form preferrably directly into the user registration form and so when the user clicks register, it also submits/creates the tripal content of that specific type.

Tagging: @spficklin @bradfordcondon @mestato @shawnawsu 

Thanks!

**Comment by spficklin** [comment]
Can you provide a bit more details?  For example, are you wanting to submit a record to the Chado `contact` table(s) when someone signs up for the site?

**Comment by risharde** [comment]
Hi @spficklin thank you for responding, yes that's exactly it. What we have built is a module that creates "Tripal Contact Profile"(s) which populates the contact and contactprop tables in chado. It works fine standalone but we'd like to for a better word 'force' the user to enter data during registration. So  basically we'd like to add the tripal entity submission form (the fields essentially) into the user registration form if possible, not sure if that's possible. The only way I've been able to accomplish this is a dirty iframe hack which we don't think best suites it as you may also agree. Any advice or ideas on this?

**Comment by spficklin** [comment]
I don't think that's possible to do without custom code.  The reason is that Tripal manages the entities that it creates (e.g. gene, publication, contact, etc), and Drupal manages the entities it creates (users, node, story, etc.).  I think you'd need to do is 

1.  Add the fields to your registration page.
2.  Write a module that implements the [hook_user_insert](https://api.drupal.org/api/drupal/modules%21user%21user.api.php/function/hook_user_insert/7.x) hook.
3.  When a new user is added, pull the information from the submitted form and either
     - create a new contact in Chado
     - update an existing contact in Chado.
4.  You can also implement the [hook_user_update](https://api.drupal.org/api/drupal/modules%21user%21user.api.php/function/hook_user_update/7.x) so that if a user updates their information it gets duplicated in the chado table.

The problems with this approach are:
1.  You'd be storing duplicated information (once in Drupal with the user profile and a copy in Chado).  This can cause a data integrity problem if they ever get out of sync, but as long as your code is bug free and well tested there shouldn't be a problem.
2.  How do you resolve if a user already exists in the contact table?  Can you match an existing contact with a new user, or would you wind up with duplicates.... not an easy problem to figure out.

**Comment by spficklin** [comment]
On second thought.... It may be possible to embed a form form one entity type onto another entity type. But I'm not entirely sure how to do that.  @shawnawsu thoughts?

**Comment by risharde** [comment]
Thanks @spficklin , your detailed post is exactly what I thought and what I was trying to avoid for maintenance reasons (duplicate data, fields etc) but not off the books considering we want the best user experience possible. I'll await for @shawnawsu 's response on whether the embed form is a possibility or not and work from there. Thank you so much for your speedy response, really appreciated!

**Comment by bradfordcondon** [comment]
Could you use something like the ctools wizard to have step 1) register, step 2) fill out the contact entity form, best case scenario with values pre-populated from step 1? 

I had started work on this but stopped due to falling out of scope.  I was thinking a contact_drupal linker table to prevent double-storing any information.

I agree with Stephen that theres no clean and easy solution.

**Comment by shawnawsu** [comment]
Embedding a form within a form isn't allowed or good practice but Bradford's suggestion makes sense. Have you thought about putting the chado specific data fields in the user profile and creating a small function that just checks the field's been filled out before allowing the person to perform any functions on the site? I'm making the assumption they'll be doing something on your site and not just registering for emails or the like.

**Comment by risharde** [comment]
thanks @bradfordcondon and @shawnawsu I have been looking at the ctools wizard to see if that would be a solution. Thank you so much for responding. I won't know if that works until I do some extensive testing of the wizard, if it does, I'll update this question accordingly!

Thanks again for all you help!
Risharde

**Comment by spficklin** [comment]
Thanks @risharde for the question.  Since you are going to look into this further I'm going to close out the issue. Please respond back if you find a solution!
