### ISSUE TITLE
Analysis records should not be required by loaders.

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#93]
The analysis table of chado is a bit inflexible and can't store everything about a protocol.   Rather than requiring an analysis for loading data perhaps we should just ask for meta data annotations that get stored in somewhere.....  Let's discuss

**Comment by laceysanderson** [comment]
Specifically, one restriction relates to the fact that a file often results from multi-step pipelines. Which program do you highlight in the analysis table directly since you can only mention one program/version. 

One approach may be to make the analysis record reflect the pipeline as whole but then where do you store the components of the pipeline? Using the analysisprop table can be restrictive if you want to store program name, version, source file and keep track of which goes with which step in the pipeline it can get messy...

One suggestion might be to utilize relationships between analysis records?

**Comment by spficklin** [comment]
One recommendation may be that the entire pipeline is the analysis and that the pipeline description can be documented with the analysis. What do you think of that approach?

**Comment by bradfordcondon** [comment]
Analyses are optional on Importers and I'm therefore closing this.  I think we've got discussion elsewhere on the analysis vs project side of things, but if we want to continue here please re-open.
