### ISSUE TITLE
Is there any one installed Tripal on OS other than Ubuntu or CentOS?

### ISSUE THREAD

**Issue by EugeneKim76** [tripal/tripal#936]
Dear all,
Recently, I attempt to install Tripal on openSUSE.
However,  I failed to install Tripal from the first step.
I failed to install httpd as shown in the manual in Tripal.info.
The manual shown in Tripal.info is based on Ubuntu and CentOS7.
I want to follow the manual, however, it is hard to install new OS on our server.
Is there any one installed Tripal on openSUSE?
Is there any problem to install Tripal on OS other than Ubuntu or CentOS7?
Should I have to install Ubuntu or CentOS7?
Best,

**Comment by bradfordcondon** [comment]
I imagine you can install Tripal on openSUSE, but will need to use that operating system's specific commands for installing packages. The server setup section is installing and configuring apache/http, php, and postgres.  You could try following a guide on [setting up that stack for openSUSE](https://en.opensuse.org/SDB:LAMP_setup) and then [starting the guide at the drush installation step](https://tripal.readthedocs.io/en/latest/user_guide/install_tripal/drush_installation.html).

That said, if you aren't very familiar with systems administration, i recommend you start with Ubuntu or CentOS, if only because you'll be able to get more support from the Tripal community.

**Comment by EugeneKim76** [comment]
Thanks for kind reply.
I will add comments when I have a better understanding of this issue.
Best

**Comment by spficklin** [comment]
@EugeneKim76 just checking to see if you were successful with OpenSUSE?
