### ISSUE TITLE
How to manage users access to Tripal content views

### ISSUE THREAD

**Issue by Yosra3** [tripal/tripal#966]
Hi 
I created different views on Tripal but only the admin has access to the content. 
Please how can i grant access right to all  authenticated user ? 

Thank you

**Comment by laceysanderson** [comment]
How to change permissions on views: Edit the view and change the "permission" settings as shown in the screenshot.
<img width="1417" alt="Screen Shot 2019-06-27 at 9 24 55 AM" src="https://user-images.githubusercontent.com/1566301/60279348-1da3e800-98be-11e9-809e-2aa501720c86.png">
<img width="811" alt="Screen Shot 2019-06-27 at 9 27 22 AM" src="https://user-images.githubusercontent.com/1566301/60279358-21376f00-98be-11e9-85c2-f464dc21e3e3.png">

How to change permissions on content in general (so that authorized users can see the pages not just the search):
1. Go to Admin > People > Permissions tab
2. Find the entry for the Tripal Content you are interested in.
3. Click the checkbox beside the permissions you would like ot grant (e.g. all authenticated users can see gene Tripal content pages.
<img width="1225" alt="Screen Shot 2019-06-27 at 9 33 28 AM" src="https://user-images.githubusercontent.com/1566301/60279671-bdfa0c80-98be-11e9-9603-7b103fbab66a.png">
4. Click "Save Permissions"

Hopefully that helps!

NOTE: Assuming you are using Tripal 3. If using Tripal 2 it's the same process except the names of the permissions for the second set are different.

**Comment by spficklin** [comment]
@Yosra3 does @laceysanderson 's response address your question?  Let us know and we can close this issue out if so, and if not we can help more.

**Comment by bradfordcondon** [comment]
looks like this question was answered.  If you still have questions please feel free to comment and I'll re-open.
