### ISSUE TITLE
after Tv2 data migration, views can't find cv table

### ISSUE THREAD

**Issue by srobb1** [tripal/tripal#969]
Hello,

I finally managed to upgrade from Tv2 to Tv3 (7.x-3.2). We followed the steps for the migration. Now the first thing I wanted to try is to add a new content type. I want to check to see if the term gene_group(SO:0005855) is in the db. I go to both 'Mange Chado CV Terms' and 'Manage Chado CVs'. I try to do a search with no filters to get the full list back, but I get nothing. I do into 'edit view' and when I try the search from within the edit screen, I get this error in both views:

```SQLSTATE[42P01]: Undefined table: 7 ERROR: relation "cv" does not exist LINE 5: cv cv) subquery ^```

How do I make sure Drupal "sees" the chado tables? What should I try to figure out what is missing?

Thank you,
Sofia

**Comment by spficklin** [comment]
> I finally managed to upgrade from Tv2 to Tv3 (7.x-3.2) 

:tada:

If you are getting nothing back from the "Manage Chado CV Terms" it may be because you've updated the Views module recently and you need to reapply the Views patch. See instructions here: 
 https://tripal.readthedocs.io/en/latest/user_guide/install_tripal/manual_install/install_tripal.html#apply-patches.

The message `Undefined table: 7 ERROR: relation "cv"` is a bit odd.... If you are getting that and the patch isn't the fix.  Then we need to dig deeper.

**Comment by bradfordcondon** [comment]
hi @srobb1 this should have been resolved by @spficklin PR #972 (hopefully).  Can you update Tripal and retest?

**Comment by srobb1** [comment]
Sorry for the long delay. Once we were able to overcome our issues with updating Chado from 1.2 -> 1.3 #970 we no longer had this problem.
