### ISSUE TITLE
Monthly User's Meeting Format Change

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#984]
This issue is to request comments for a suggested change to the monthly Tripal User's Meeting.  Now that we have a formal Project Management Committee (PMC) and a formal Tripal Advisory Committee (TAC) and we are using GitHub for core functionality discussions, it has been suggested that we change the meeting format to help build synergies between different Tripal User's.   Here's the suggested format:

1) 5-15 minutes for the PMC to provide updates and respond to questions about Tripal core development and features. 
2) 5-15 minutes for the TAC chair or co-chair (if needed) to conduct business of the TAC.
3) 30-45 minute presentation from anyone in the community including training and demonstration of an extension module, discussion of a related topic of interest.  

In order to limit the number of meetings that folks have, the User's meeting will be postponed once a quarter in favor of a TAC meeting.

Thoughts, suggestions?

**Comment by mestato** [comment]
Just to clarify item 2, I think asking the TAC to show up to every meeting is unrealistic for some members. So it would be the TAC chair and any other present members getting feedback from the community. I just want this clarity as the Tripal governance document (https://tripal.readthedocs.io/en/latest/contributing/governance.html) specifies TAC members meet once a quarter. Since we've barely gotten off the ground and I just got all these lovely but very busy people to agree to serve, I'd hate to bearer of news that we have 12 meetings a year instead of 4.  :)

Lets clarify that agenda item to be 5-15 minute section where the community voices issues or discussion for the next TAC meeting (but not TAC business or decision making, which will be conducted at the quarterly TAC meetings and involve the entire TAC). I'll take notes and use them to create the TAC meeting agendas and github issues for further comment.

**Comment by spficklin** [comment]
Yes, I agree @mestato. Sorry if that was confusing. It was meant to mean 5-15 minutes of time set aside for TAC if they wanted to communicate anything to the larger Tripal community. But it can certainly be a discussion of item the community might want to bring to the attention of the TAC as well.

**Comment by bradfordcondon** [comment]
no disagreement so I'm closing this.  See y'all in the new format!
