### ISSUE TITLE
Can't "sudo su - postgres": Get "This account is currently not available."

### ISSUE THREAD

**Issue by mdhar1980** [tripal/tripal#991]
Hello,

I've been having some issues with restoring a backup of my postgres db to a VM (development instance: see here: https://github.com/tripal/tripal/issues/989#issuecomment-525779743).

So I wanted to create a test database on our production server. However, I'm unable to change to the postgres user, as described here: https://tripal.info/tutorials/v2.x/installation/drupal

I get "This account is currently not available."

I can't figure out why that would be the case, as I would have used that command to create the original database.

Thanks for any help.

My version details:
Site version info:
Tripal Version: 7.x-2.1
Drupal Version: 767
PostgreSQL Version: PostgreSQL 10.10 (Ubuntu 10.10-0ubuntu0.18.04.1)
PHP Version: 7.2.19-0ubuntu0.18.04.2

**Comment by bradfordcondon** [comment]
https://unix.stackexchange.com/questions/441683/why-cant-i-su-postgres

Have you tried some of the suggestions here such as `sudo -u postgres -i` or giving ~~your `postgres` user a password~~ edit---- nevermind thats a security hole apparently, dont give the user a password.

Your issue is definitely a systems level permission one though

**Comment by bradfordcondon** [comment]
this is a Drupal/postgres config issue not Tripal, and I havent heard back so I'm closing the issue.  Let us know if you still need help.
